### PR TITLE
Use of Vector Drawable Instead of PNGs #114

### PR DESCRIPTION
**Pull request by doomers**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

#114 done.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@doomers  Please follow the Commit Style guide line. check out the project wiki.

**Comment by doomers** [comment]
Okay, I will  follow all the guidelines from next times , and will do changes tomorrow in this PR.

**Comment by doomers** [comment]
@therajanmaurya Please review this.

**Comment by therajanmaurya** [comment]
@doomers Still you are not following the commit guidelines. Please read carefully and make the commit message as accordingly https://github.com/openMF/self-service-app/wiki/Commit-Style-Guide

**Pull request merged**
