### PR TITLE
Fix: GuarantorApi was not getting created in BaseApiManager Class

### PR DESCRIPTION
**Pull request by shahnoor-khan**
In BaseApiManager class guarantorApi was not getting called correctly instead  a different field was getting called, which wasn't creating the guatrantorApi. So I made a change, which make sure it create guarantorApi.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shahnoor-khan** [comment]
@jawidMuhammadi I checked the baseApiManager class and the guarantorApi was not getting created, I don't know if that was intentional or a bug. Can you please review it?

**Review by jawidMuhammadi — CHANGES_REQUESTED** [review]
Squash your commits, please

**Comment by shahnoor-khan** [comment]
I tried doing that but its not working because I pulled multiple commits into that branch by mistake, could please check the file changes that I made because I don't think I made any changes apart from that 1 file.

**Comment by PratyushSingh07** [comment]
As discussed @therajanmaurya , I have opened PR #2279 in place of this PR. We can close this down\

**Pull request closed without merging**
