### PR TITLE
Fix #579 : Visibility Icons changed in Account Overview

### LINKED ISSUE #579: Changing Hidden icon of Account Overview in the Home Section
**Summary:**

The Previous icon of Hidden Account Overview is just the faded version of Show icon , which gives less sense to the logic of appearing and disappearing.
**Steps to reproduce:**

Clicking the Show Account Overview on the home page.

**Expected behaviour:**

Having a better icon to imply the details Best.
.

**Device and Android version:**
6.0.1 API 23
**Screenshots:**

Using this icon as Hidden Purpose
new icon

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #579 

pr579

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@therajanmaurya Review this PR and check why build is failing as it passing in my Studio.

**Comment by therajanmaurya** [comment]
@miPlodder Please fix the Travis failing

**Comment by miPlodder** [comment]
@therajanmaurya It passing on my machine.

**Comment by miPlodder** [comment]
@therajanmaurya I have fixed it. Travis was failing because some dependencies were added in the last merge, so I rebased the branch.

**Pull request merged**
