### PR TITLE
feat:added filters in savings account transaction section

### LINKED ISSUE #735: feature:add filters for deposit and withdrawal  in savings account transaction section
**Summary:**
In savings account transactions the list is too long for some account.So it would be better if we add a filter for withdrawal and deposit, it would be much easier go through the transactions.

**Screenshots**
screenshot_20180314-232927

### LINKED ISSUE #745: Message in case of no beneficiaries
**Summary**
If no beneficiary is added then the screen should show an appropriate message.

**Steps to reproduce:**
Go to the benfeciary section of the app.

**Expected behaviour:**
The screen is blank.

**Screenshots:**

screenshot_2018-03-18-12-03-45-464_org mifos mobilebanking

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #735

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ivary43** [comment]
@therajanmaurya , @dilpreet96  please review.

**Comment by prashantkh19** [comment]
@ivary43 can you resolve the merge conflicts?

**Comment by prashantkh19** [comment]
@ivary43 We can also add the date filter to the dialog box. Refer #1162

**Comment by prashantkh19** [comment]
@therajanmaurya close this

**Comment by prashantkh19** [comment]
Will be taken up during GSoC '19 work.

**Pull request closed without merging**
