### PR TITLE
Correct spelling mistake

### LINKED ISSUE #455: Minor  Spelling Mistakes
When you go to Home page>Accounts>Loan (or Saving or Share) and if client has no accounts , the message shows:
Their is no SavingsAccount associated with you.
Their is no LoanAccount associated with you.
Their is no ShareAccount associated with you.
Their is no transactions associated with you(In Recent Transactions)

It should be 'There' .

You have to correct the spellings from this line: https://github.com/openMF/mifos-mobile/blob/development/app/src/main/res/values/strings.xml#L123 to this line https://github.com/openMF/mifos-mobile/blob/development/app/src/main/res/values/strings.xml#L127

### PR DESCRIPTION
**Pull request by ghost**
Fixes #455 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@siddharth2010 Please follow the commit guidelines: https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide.
your commit message should be `style: Correct spelling mistake`

**Comment by therajanmaurya** [comment]
@siddharth2010 Make the changes ASAP.

**Comment by ghost** [comment]
I am so sorry. Just a sec. I will fix it in a minute

**Comment by ghost** [comment]
done!

**Comment by dilpreet2028** [comment]
Good work @siddharth2010

**Pull request merged**
