### PR TITLE
Feat: Added Hindi Translated Strings

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixes #2365 

Added Hindi Translations for the Strings.

Please add #hacktoberfest on merge.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
please follow our commit & PR guidelines . you can go through the wiki page  [here](https://github.com/openMF/mifos-mobile/wiki)

Follow the same in all of your PRs

**Comment by SekhGulamMainuddin** [comment]
> please follow our commit & PR guidelines . you can go through the wiki page [here](https://github.com/openMF/mifos-mobile/wiki)
> 
> Follow the same in all of your PRs

Sorry for it.
I will follow the guidelines. But will this PR be accepted or not?

**Comment by PratyushSingh07** [comment]
> I will follow the guidelines. But is this PR valid or not.

Without following the proper guidelines this PR cannot be deemed valid

**Comment by SekhGulamMainuddin** [comment]
> > I will follow the guidelines. But is this PR valid or not.
> 
> Without following the proper guidelines this PR cannot be deemed valid

then what changes should I do?
 Like should I add screenshots?

**Comment by PratyushSingh07** [comment]
you dont need to close the issue everytime @SekhGulamMainuddin . To change the commit message you can use the `git commit --amend` command and to change the PR message you can simply edit the PR text

**Comment by SekhGulamMainuddin** [comment]
> you dont need to close the issue everytime @SekhGulamMainuddin . To change the commit message you can use the `git commit --amend` command and to change the PR message you can simply edit the PR text

ok I will keep that in mind from next PR onwards. And follow the rules.

**Comment by PratyushSingh07** [comment]
> then what changes should I do? Like should I add screenshots?

I am not talking about the screenshots, please go through the wiki section and look at the manner in which you have to submit a PR. For instance, your commit message should have been feat #2365: hindi translations for mifos mobile"

**Comment by SekhGulamMainuddin** [comment]
> > then what changes should I do? Like should I add screenshots?
> 
> I am not talking about the screenshots, please go through the wiki section and look at the manner in which you have to submit a PR. For instance, your commit message should have been feat #2365: hindi translations for mifos mobile"

OK I am changing the commit message.

**Comment by SekhGulamMainuddin** [comment]
Thanks @PratyushSingh07 I have changed the commit message.

**Comment by PratyushSingh07** [comment]
It's more of a feat than a fix . It's ok for the time being but make sure to write proper prefixes while submitting a PR.

I have changed the PR message, follow the same for rest of your PRs

**Comment by SekhGulamMainuddin** [comment]
Sure, I will follow the rules and guidelines.

**Comment by PratyushSingh07** [comment]
I have reviewed this PR  @therajanmaurya , I believe this will be a good addition to our project

**Comment by SekhGulamMainuddin** [comment]
Hi @therajanmaurya can you please add `hacktoberfest-accepted` tag because its compulsory for Hacktoberfest Verification.

**Pull request merged**
