### PR TITLE
refractor: Add mifos passcode library

### PR DESCRIPTION
**Pull request by dilpreet2028**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@dilpreet96 Asking for Permissions is not there.

**Comment by dilpreet2028** [comment]
@miPlodder What permission are you talking about?

**Comment by miPlodder** [comment]
@dilpreet96 Asking for Phone Permissions on Passcode Activity.

**Comment by dilpreet2028** [comment]
@miPlodder Thanks for informing.

**Comment by therajanmaurya** [comment]
Good work!!

**Pull request merged**
