### PR TITLE
    feat:Add feature to show user details

### PR DESCRIPTION
**Pull request by hardik124**
1)Add layout in Navigation Header to show logged in user profile image and name.

          2)  Onclick profile ImageView opens a Layout that shows the user profile.

          https://github.com/openMF/self-service-app/issues/64
#64 
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rahulbabbar1** [comment]
@hardik124 travis ci build failed. Did you run ./gradlew check ??

**Comment by hardik124** [comment]
https://github.com/travis-ci/travis-ci/issues/7110 
I am unable to use Build tools <25 as it shows version too low , and travis CI fails with build tools 25 due to license agreement problem.

@therajanmaurya  can you tell me what should i do?

**Comment by hardik124** [comment]
@rahulbabbar1  .gradlew/check completes successfully .

**Comment by m-murad** [comment]
@hardik124 
I think you need to update `travis.yml` because of changing build tool version.
Discuss this with project maintainers.

**Comment by hardik124** [comment]
I am closing this one ,will send after resolving this.

**Pull request closed without merging**
