### PR TITLE
Fix #1259 - No CI

### LINKED ISSUE #1259: No CI
There is no Continuous Integration script other than travis

### PR DESCRIPTION
**Pull request by s-ayush2903**
Fixes #1259 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
@geekanamika Please review it.

**Review by ShivangiSingh17 — COMMENTED** [review]
Better is to name the directory as ```.circleci```

**Comment by s-ayush2903** [comment]
Updated @ShivangiSingh17

**Comment by miPlodder** [comment]
Not needed now. Github Actions should be suffice.

**Pull request closed without merging**
