### PR TITLE
Fix: background color of splash screen doesn't change with theme #2466

### LINKED ISSUE #2466: Bug: background color of splash screen doesn't change with theme
**Summary:**

splash screen reamins light mode even in dark mode.

**Expected behaviour:**

it should be in dark mode if the app is in dark mode

**Screenshots:**
[Screen_recording_20240101_222318.webm](https://github.com/openMF/mifos-mobile/assets/136256522/0b74c53a-9901-4755-9b55-59602c473851)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

### PR DESCRIPTION
**Pull request by Maan-Sharma**
Fixes #2466

https://github.com/openMF/mifos-mobile/assets/146059379/b71d66e1-4995-49a6-aa1e-108aadfa0425
 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Maan-Sharma** [comment]
@PratyushSingh07  have a look!!

**Comment by PratyushSingh07** [comment]
Please log in to the app with the demo credentials and check if it works after you have changed the theme from inside of the app

**Comment by Maan-Sharma** [comment]
I don't get it what you
 want to say @PratyushSingh07

**Comment by Maan-Sharma** [comment]
its work but in app register page didn't change its theme and I think its a new issue or features ,However this work fine
 @PratyushSingh07

**Comment by PratyushSingh07** [comment]
Awesome , could you please attach a video just so I can cross check

**Comment by Maan-Sharma** [comment]
ok

**Comment by Maan-Sharma** [comment]
https://github.com/openMF/mifos-mobile/assets/146059379/a35a1873-7c09-448e-9e96-ddcbcea5db04

look!!

**Comment by PratyushSingh07** [comment]
> Please log in to the app with the demo credentials and check if it works after you have changed the theme from inside of the app

Did you not understand what I wrote here @Maan-Sharma . I specifically asked you to log into the app with the credentials and then change the theme from the settings. Right now you are just changing the system theme and that's it

**Comment by Maan-Sharma** [comment]
ohh , where i get the log credentials?  can you give me the link or something @PratyushSingh07

**Comment by Maan-Sharma** [comment]
hey @PratyushSingh07  can you give me demo log credentials??

**Comment by PratyushSingh07** [comment]
Go through readme.md

**Comment by Maan-Sharma** [comment]
I found it

**Comment by Maan-Sharma** [comment]
its not changing inside the app , I gusse  for working with the app theme we have to migrate in compose @PratyushSingh07 or if anything I'm missing out please tell me

**Comment by PratyushSingh07** [comment]
> its not changing inside the app , I gusse for working with the app theme we have to migrate in compose @PratyushSingh07 or if anything I'm missing out please tell me

Not sure if migrating the splash screen to compose is a good idea. We can just use the api if needed. Moreover, the issue may be because of the ui library. So are you still going to solve this issue or should I close this PR ?

**Comment by Maan-Sharma** [comment]
@PratyushSingh07  can you tell me how I work with App Ui

**Comment by Maan-Sharma** [comment]
@PratyushSingh07    I add api and make changes in Splash screen too but I could't  find out the problem 
package org.mifos.mobile.ui.activities

import android.content.Intent
import android.os.Build
import android.os.Bundle
import androidx.core.splashscreen.SplashScreen.Companion.installSplashScreen
import com.mifos.mobile.passcode.utils.PasscodePreferencesHelper
import org.mifos.mobile.R
import org.mifos.mobile.api.local.PreferencesHelper
import org.mifos.mobile.ui.activities.base.BaseActivity
import org.mifos.mobile.ui.fragments.applySavedTheme
import org.mifos.mobile.ui.login.LoginActivity
import org.mifos.mobile.utils.Constants

/*
* Created by saksham on 01/June/2018
*/
class SplashActivity : BaseActivity() {

    private var passcodePreferencesHelper: PasscodePreferencesHelper? = null

    override fun onCreate(savedInstanceState: Bundle?) {

        val intent: Intent?
        super.onCreate(savedInstanceState)


        // Determine the current mode (light or dark)
        val isDarkMode = isDarkMode()

        // Set the theme based on the mode
        val themeId = if (isDarkMode) R.style.SplashTheme_dark else R.style.SplashTheme
        setTheme(themeId)

        // Install splash screen
        installSplashScreen().apply {
            // Customize splash screen if needed
        }

        passcodePreferencesHelper = PasscodePreferencesHelper(this)
        if (passcodePreferencesHelper?.passCode?.isNotEmpty() == true) {
            intent = Intent(this, PassCodeActivity::class.java)
            intent.putExtra(Constants.INTIAL_LOGIN, true)
        } else {
            intent = Intent(this, LoginActivity::class.java)
        }
        startActivity(intent)
        finish()


    }
    private fun isDarkMode(): Boolean {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            resources.configuration.uiMode and android.content.res.Configuration.UI_MODE_NIGHT_MASK == android.content.res.Configuration.UI_MODE_NIGHT_YES
        } else {
            false // For versions older than Android Q, assume light mode
        }
    }
}

**Comment by PratyushSingh07** [comment]
I will look into it in my spare time . Meanwhile I am converting this PR to draft

**Comment by Vikashgathala** [comment]
can i work on this @PratyushSingh07 ? I'll complete this as soon as possible.

**Comment by PratyushSingh07** [comment]
> can i work on this @PratyushSingh07 ? I'll complete this as soon as possible.

I don't have a say. Ask @Maan-Sharma

**Comment by PratyushSingh07** [comment]
closing due to inactivity. Reopen the PR if you make any progress

**Pull request closed without merging**
