### PR TITLE
fix:added pre-population of loan amount while loan repayment

### LINKED ISSUE #808: Loan repayment should pre-populate with amount due like in Web App
**Summary:**

When repaying a loan, the amount due should pre-populate with the current amount due like in the web app.

**Steps to reproduce:**

Navigate to a loan, click to repay.

**Expected behaviour:**

Value in the payment field pre- populated with the amount due, i.e. current installment plus any amount overdue, penalties, etc.

This should be a value in the database. See what is returned in web app to know the database values

**Observed behaviour:**

Just a blank value of zero.

**Screenshots:**
screenshot_20180415-075524

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #808

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ivary43** [comment]
@therajanmaurya, @dilpreet96  please review

**Comment by miPlodder** [comment]
@ivary43 PR looks good. Just fix the conflict. I will merge it.

**Comment by prashantkh19** [comment]
@ivary43 Can you fix the merge conflicts?

**Comment by therajanmaurya** [comment]
Fixed #1174

**Pull request closed without merging**
