### PR TITLE
Redesign: UI

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Cont. PR of UI redesign.

Work left:
Adding new beneficiary activity and third party transfer. 
frame_129_delay-0 14s(1)

frame_129_delay-0 14s

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by devansh-299** [comment]
@ShivangiSingh17 the build is failing because of the following error `/home/travis/build/openMF/mifos-mobile/app/src/main/java/org/mifos/mobile/ui/Profile.kt: (51, 43): Unresolved reference: BeneficiariesActivity`. For more details you can refer the log file from [here](https://travis-ci.com/github/openMF/mifos-mobile/builds/180984476)

**Comment by ShivangiSingh17** [comment]
@devansh-299 Will resolve them and get back

**Comment by garvit984** [comment]
@ShivangiSingh17 Please remove these conflicts so that we can merge this PR.

**Comment by PratyushSingh07** [comment]
This ui design pr can also be closed @therajanmaurya

**Comment by PratyushSingh07** [comment]
Currently we do not have any new design for mifos mobile and changing only a few sections of the app will make it look odd , hence we can close this down @therajanmaurya

**Pull request closed without merging**
