### PR TITLE
fix#1309 - Added option to skip setup passcode

### LINKED ISSUE #1309: Skip passcode
**Summary:**

Currently when user chooses to skip passcode login then he needs to login via usual username and password but still after that user is greeted with "Set-Up Passcode" screen every time he tries to use the app . So if a user doesn't want to set up passcode ever this screen shouldn't be displayed for him/her until and unless he/she changes her mind.

**Steps to reproduce:**

* Clear data of app (if not running for the first time)
* Login in into the app
* Press "Skip" on the setup passcode screen -> Complete rest of the process
* Relaunch the app -> fill login details
* See that setup passcode screen appears everytime

**Expected behaviour:**

The setup passcode screen shouldn't be displayed everytime until and unless user wants to setup/use passcode verification

**Observed behaviour:**

The setup passcode screen is displayed every time the user tries to login in into the app if he doesn't want passcode login

**Device and Android version:**

Xiaomi PocoF1
Android 9
Stock Rom

### PR DESCRIPTION
**Pull request by devansh-299**
Fixes #1309

Screen Recording

GIF-200204_233057

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Grandolf49** [comment]
Hey @devansh-299 You have some PMD rule violations. Did you run ./gradlew before creating the PR?
You can find the exact violations in this file here: mifos-mobile/app/build/reports/pmd/pmd.html

**Comment by devansh-299** [comment]
> 
> 
> Hey @devansh-299 You have some PMD rule violations. Did you run ./gradlew before creating the PR?
> You can find the exact violations in this file here: mifos-mobile/app/build/reports/pmd/pmd.html

I ran the tests but when I checked pmd.html it says "File Line Problem". What does this mean?

**Comment by ShivangiSingh17** [comment]
@devansh-299 If we allow the user to skip passcode then everytime the user wants to access either the user can access the application directly or he has to login again once he logouts.

**Comment by devansh-299** [comment]
> @devansh-299 If we allow the user to skip passcode then everytime the user wants to access either the user can access the application directly or he has to login again once he logouts.

Yes, if we allow the user to skip passcode, then he/she will need to login everytime with his/her 
credentials.

**Comment by ShivangiSingh17** [comment]
@devansh-299 having on the option of ```Skip``` after login allows the user with the option for skipping passcode.

**Comment by devansh-299** [comment]
> @devansh-299 having on the option of `Skip` after login allows the user with the option for skipping passcode.

Yes, but then every time he/she will need to press that `Skip` button. The point of this pull request was to allow users to  skip passcode login until he/she enables it back again from the settings.

**Comment by luckyman20** [comment]
Has conflict issues.

**Pull request closed without merging**
