### PR TITLE
refractor:Accounts UI improvements

### PR DESCRIPTION
**Pull request by dilpreet2028**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
Great job @dilpreet96. Your next task is to implement the material design in the whole app.
Let me know when we can talk about material design.

**Comment by dilpreet2028** [comment]
@therajanmaurya we can have a talk anytime you want.

**Comment by therajanmaurya** [comment]
Let's talk tomorrow. I will let you know the time on slack.

**Comment by therajanmaurya** [comment]
And make requested changes in other PR's then I will merge then today So We can talk about Github Pre-release too.

**Comment by dilpreet2028** [comment]
Yes, I am working on them

**Pull request merged**
