### PR TITLE
Improved Home screen, added contact icon

### LINKED ISSUE #1223: Improve the UI of the homescreen
**Summary:**

There is a scope of UI improvement in the home screen of the app
Icons can be made smaller
Visit [this](https://dribbble.com/shots/7587490-MOLLET-Wallet-app-UI-Kit/attachments/372728?mode=media) for reference

**Steps to reproduce:**

Open the app

**Expected behaviour:**

Icons can be made smaller, Othe UI improvements will be appreciated

**Observed behaviour:**

Currently, the home screen has a scope of UI improvements

**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Screenshots:**

Open the app

**This issue is for GCI Students**

### PR DESCRIPTION
**Pull request by PiyushSharma99**
Fixes #1223 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PiyushSharma99** [comment]
@GovindDixit @jddeep @santoshconflux Please review and approve. Thanks!

**Review by jddeep — APPROVED** [review]
Looks good enough :+1:

**Review by GOVINDDIXIT — APPROVED** [review]
Looks Good 👍

**Comment by GOVINDDIXIT** [comment]
@PiyushSharma99 You have to claim the issue using your GCI portal before working on any issue. You haven't claimed this issue by now

**Comment by PiyushSharma99** [comment]
@GOVINDDIXIT Please refer here - https://codein.withgoogle.com/dashboard/task-instances/5348113154310144/

**Comment by PiyushSharma99** [comment]
@GOVINDDIXIT I see another task instance here https://codein.withgoogle.com/dashboard/task-instances/6583771998978048/
Can you please suggest any more UI changes in the home screen. I have claimed it and shall work on it.

**Comment by GOVINDDIXIT** [comment]
@PiyushSharma99 There was some confusion caused due to duplicate tasks, I have updated the task instance it is now related to mifos mobile cn app https://github.com/openMF/mifos-mobile-cn. Feel free to work on it.

**Pull request closed without merging**
