### PR TITLE
Fix #2357 FilterIcon tint color

### LINKED ISSUE #2357: Tint of Filter icon isnt visible in dark mode
**Summary:**

Tint of Filter icon is  on the darker side hence it isnt visible in the dark mode

**Steps to reproduce:**
- Go to Accounts
- Click on any Active Savings account from the list
- Click on Transactions
- Filter icon on the top right corner isnt visible in dark mode

**Expected behaviour:**

Filter icon on the top right corner should have been visible in dark mode

**Observed behaviour:**

 <table>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

**Device and Android version:**

Device: Pixel 7
Android: 13

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixed #2357
Filter Icon tint color fixed.

Please add #hacktoberfest on merge.

Screenshots:
<p>
 android
 android
</p>

### CODE REVIEW

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya please merge my PR.
Please add hacktoberfest tags on merge.

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya please merge my PR.
Please add hacktoberfest tags on merge.

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 can you please review this PR

**Comment by PratyushSingh07** [comment]
@therajanmaurya please merge this PR , I have reviewed this and it follows all of the guidelines

**Comment by PratyushSingh07** [comment]
@therajanmaurya please merge this PR , I have reviewed this and it follows all of the guidelines

**Pull request merged**
