### PR TITLE
Fix #1686: Redesign of UI

### LINKED ISSUE #1686: Redesign of UI
**Summary:**
Extra-large text-view of currency

**Steps to reproduce:**
How can we reproduce the issue?
Open Update Loan Activity

**Expected behaviour:**
Medium Size Textview of currency

**Observed behaviour:**
Extra Large TextView of currency

**Device and Android version:**
Any

**Screenshots:**

### PR DESCRIPTION
**Pull request by ritish099**
Fixes #1686

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by PatelVatsalB21 — CHANGES_REQUESTED** [review]
@ritish099 can we also adjust text size of principal amount to match spinner text size `android:textAppearance="@style/Base.TextAppearance.AppCompat.Medium`. 

Didn't it look different than surrounding?

**Comment by ritish099** [comment]
@PatelVatsalB21 doing it

**Review by miPlodder — APPROVED** [review]
Good Job

**Pull request merged**
