### PR TITLE
 Style #606: added missing item closing tag </item> 

### LINKED ISSUE #606: Not proper closing of <item> tag in string.xml
**Summary:**

Not proper closing of <item> tag in string.xml, shows improper answer in **Help Fragment**

**Steps to reproduce:**

1) Open Navigation Drawer.
2) Go to to Help
3) Expand last question, you will see incomplete answer.

**Expected behaviour:**

Complete answer to the question

**Observed behaviour:**

Incompleted answer to the question

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

_new

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #606 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by dilpreet2028** [comment]
Please fix the conflicts @miPlodder

**Comment by dilpreet2028** [comment]
@miPlodder I don't want the merge comment so can you please revert back (hard reset) back to your commit and then rebase it with development branch.

**Comment by miPlodder** [comment]
@dilpreet96 Please review again, I have made the changes.

**Comment by dilpreet2028** [comment]
@miPlodder can you change your commit message according to the guidelines : https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide#the-type

**Comment by miPlodder** [comment]
@dilpreet96 Please review again, I have changed the commit message.

**Comment by miPlodder** [comment]
@dilpreet96 I have made the requested changes. Please review again.

**Pull request merged**
