### PR TITLE
Refactor: Improve UX and use thousands separators

### PR DESCRIPTION
**Pull request by karsai1993**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

This pull request includes improvement of UX and usage of thousands operator (which is related to the UX).  For thousands separator, I implemented a method which does this function. For UX, there are some little changes in some classes.
See attached images:
improved_unparseable
imp_sum2
imp_sum1
imp_repayment_schedule
colour_3

### CODE REVIEW

**Comment by karsai1993** [comment]
@therajanmaurya Could you please help how to handle these conflicts? Is it enough to delete the content of the conflicting file and then copy my version of that file?

**Comment by karsai1993** [comment]
Hi @therajanmaurya ! Could you please check the conflicts regarding this pull request. I would like to ask for your review on them so as to move them into the right direction. This pull request contains some important UI changes. The changes were reported in 4 issues. They should be merged so that the contributors could avoid reporting issues with the same contents as mine ones. Thanks in advance!

**Comment by dilpreet2028** [comment]
@therajanmaurya This PR contains some issues which are already fixed and some can be implemented in separate PRs.

**Comment by dilpreet2028** [comment]
Fixed in #387

**Pull request closed without merging**
