### PR TITLE
Fix:Issue #591:Improper Eye Icon behaviour in passcode activity

### LINKED ISSUE #591: Improper behaviour of eye icon in passcode activity.
**Summary:** 

Faded eye icon - hidden passcode
Dark eye icon - not hidden passcode
Initially, the eye icon should be faded since the passcode is hidden and after clicking it once it should turn to dark but this is not happening. Changing the color requires two touches after which the icon works as expected.

**Steps to reproduce:** 

1)Run the app
2)enter some number
3)hit the eye icon(password visible but color same as initial)
4)hit the eye icon(password hidden and now color works as expected)

**Expected behavior:** 

Inititial icon color should be faded since password is hidden and the color should change on a single click with beahavior.

**Observed behavior:** 

Requires two click.

**Device and Android version:** 

Android 5.0.2,API 21

**screenshots**

NOTE: we can also replace the color behaviour with striked eye icon if instructed.
I am working on this.

### PR DESCRIPTION
**Pull request by AkshGautam**
Fixes #591 

Please Add Screenshots If any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  Please review

**Comment by dilpreet2028** [comment]
Looks good! @AkshGautam Can you change the commit message to `fix: Improper Eye Icon behaviour in passcode activity`

**Comment by AkshGautam** [comment]
@dilpreet96  Done!

**Comment by AkshGautam** [comment]
@dilpreet96 I have done the changes.Please review

**Pull request merged**
