### PR TITLE
fix: Issue #456 - Due Date and Installment Amount in LoanAccountDetails

### LINKED ISSUE #456: In Loan Account Details , Next Instalment  and and Due Date are showing wrong values.
As you can see from the screenshot & Link:

Next Instalment Amount  should be 987.72 (but showing total outstanding)
Next Due Date should be 02 February 2017 (but showing disbursement date)

https://mobile.openmf.org/#/viewloanaccount/1345

screenshot_2017-10-13-15-17-27

### PR DESCRIPTION
**Pull request by fazerlicourice7**
Correct LoanAccountDetails to show the correct Due Date and Installment Amount for the next payment.
Switch the LoanAccount data object with LoanWithAssociations data object wherever relevant because of the increased information in the latter.

Fixes #456 

screenshot_20171212-205207

### CODE REVIEW

**Comment by dilpreet2028** [comment]
Hey @fazerlicourice7, there is already a PR #509 for this and it is a GCI task so closing this PR and from now first comment on issue and then send a PR for that.

**Comment by fazerlicourice7** [comment]
@dilpreet96 
Yeah. I know. I completed the GCI task and a mentor marked it as complete. This is PR #508 which means I was on this before #509. I don't know if this [link](https://codein.withgoogle.com/dashboard/task-instances/5351971714236416/) works, but that is the link to my task showing it's been approved by @therajanmaurya 

If you look at issue #456, you'll see that I commented asking for some direction, and was making contributions well before the author of #509 .

**Comment by dilpreet2028** [comment]
Sorry for the misunderstanding @fazerlicourice7 , I got confused with 2 PR's

**Comment by fazerlicourice7** [comment]
No problem :)

**Comment by luckyman20** [comment]
@fazerlicourice7 I created the PR #507 but closed it because of merge conflicts and travis failing. Then I opened another PR with some more changes and it is #509 with the support of Unit Tests and all other fragments which are connected to this Fragment.

So technically I opened the PR for this issue earlier.

Actually there were two copies of the same issue, one is mentored by Avik Ganguly and other one is mentored by Rajan Maurya. So there is lot of misunderstanding.

I had already pointed out this matter and informed @edcable

**Comment by fazerlicourice7** [comment]
So there were two copies of the task on GCI? oh. I guess that's our problem then. I've actually seen a couple of tasks that are on GCI, but when I go to the github issue, it's already been completed and closed. I think the GCI mentors should take a look at that.

**Comment by miPlodder** [comment]
@fazerlicourice7 Already Fixed.

**Pull request closed without merging**
