### PR TITLE
app introduction implemented

### PR DESCRIPTION
**Pull request by devansh-299**
Feature : Application Introduction screens

Screen Recording

GIF-200118_174940

Suggestions
* Please suggest changes for the strings and color scheme etc (if needed)
* Please suggest if any animations should be added or not

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by laxyapahuja** [comment]
It is advised to make an issue first and then send a PR.

**Comment by laxyapahuja** [comment]
Have you tested this so that it doesn't appear every time a user opens the app?

**Comment by devansh-299** [comment]
> 
> 
> It is advised to make an issue first and then send a PR.

Yeah, I will keep this in mind

**Comment by devansh-299** [comment]
> 
> 
> Have you tested this so that it doesn't appear every time a user opens the app?

Yes

**Comment by OHassini** [comment]
@devansh-299 Make sure you only include changes related to your issue, remove all the extra build gradle and manifest changes.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 Make sure you only include changes related to your issue, remove all the extra build gradle and manifest changes.

I tried updating the PR but these changes are introduced on their on own while committing

**Comment by rchtgpt** [comment]
> I tried updating the PR but these changes are introduced on their on own while committing

Changes are not introduced automatically while committing. Though there is a possibility that syncing the gradle does some reformatting. You will have to manually remove the formatted lines of code if you want your PR to be merged.

**Comment by devansh-299** [comment]
> 
> 
> > I tried updating the PR but these changes are introduced on their on own while committing
> 
> Changes are not introduced automatically while committing. Though there is a possibility that syncing the gradle does some reformatting. You will have to manually remove the formatted lines of code if you want your PR to be merged.

I don't know how it happened, but yeah I will try to resolve it

**Comment by devansh-299** [comment]
@rachittt I have updated the PR with an associated issue #1473

**Comment by rutvik-panchal** [comment]
@devansh-299 We can use viewPager2 and RecyclerViewAdapter to implement the app introduction and use only one layout for the implementation.

**Comment by devansh-299** [comment]
> @devansh-299 We can use viewPager2 and RecyclerViewAdapter to implement the app introduction and use only one layout for the implementation.

@rutvik-panchal thanks for the update. It's an old PR and I have really lost the track of it. I 
will check and get back to you :)

**Comment by luckyman20** [comment]
Old PR. Fixed in PR #2070.

**Pull request closed without merging**
