### PR TITLE
#1487-feat: Display toast for logout status

### LINKED ISSUE #1487: Show Logout status of the application
**Summary:**
When the application is logged out, there is no toast available to show the logout status.

**Expected behaviour:**
Logout status should be shown when the logout button is pressed.

**Observed behaviour:**
No toast message is displayed.

### PR DESCRIPTION
**Pull request by Sparsh1212**
Fixes #1487 

**Screenshots:**

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Sparsh1212** [comment]
@miPlodder Please review.

**Review by miPlodder — APPROVED** [review]
LGTM
can we change commit-msg  `feat #issue-id: commit-msg`

**Comment by Sparsh1212** [comment]
> LGTM
> can we change commit-msg `feat #issue-id: commit-msg`

Done!

**Comment by miPlodder** [comment]
Nice job, keep up the good work 👍

**Pull request merged**
