### PR TITLE
minor fix in spelling

### LINKED ISSUE #2324: Minor Spelling change
**Summary:**
- There's a spell error in one of the lines in Gradle file. So, corrected that.

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

What did you expect the app to do?

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**
- Samsung Galaxy A12
- Android Studio Flamingo

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

### PR DESCRIPTION
**Pull request by utkarsh006**
- Fixes #2324 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@PratyushSingh07 Kindly Review

**Comment by PratyushSingh07** [comment]
You haven't opened and issue for this PR. Moreover you havent followed our PR and commit guidelines. 
The commit message shouldnt have been `minor fix` but instead it should have been something that followed our commit guidelines. Please have a look at the Readme.md

**Comment by utkarsh006** [comment]
> You haven't opened and issue for this PR. Moreover you havent followed our PR and commit guidelines. The commit message shouldnt have been `minor fix` but instead it should have been something that followed our commit guidelines. Please have a look at the Readme.md

@PratyushSingh07 Can you check it now?

**Comment by PratyushSingh07** [comment]
Squash your commits , 3 commits is too much in this case. 
Also edit the PR to something like style: minor spelling change in build.gradle

**Comment by utkarsh006** [comment]
> Squash your commits , 3 commits is too much in this case. Also edit the PR to something like style: minor spelling change in build.gradle

@PratyushSingh07 Followed [these steps](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits-in-github-desktop) but unable to squash all the commits. Can you see it?

**Comment by PratyushSingh07** [comment]
I still see 3 commits , we generally use git rebase -i to squash the commits but i dont think that it will work in your case since you have a merge commit as well. Maybe try [this](https://stackoverflow.com/questions/30136558/how-to-squash-commits-which-have-merge-commit-in-between) and see if it works

**Comment by utkarsh006** [comment]
> I still see 3 commits , we generally use git rebase -i to squash the commits but i dont think that it will work in your case since you have a merge commit as well. Maybe try [this](https://stackoverflow.com/questions/30136558/how-to-squash-commits-which-have-merge-commit-in-between) and see if it works

@PratyushSingh07 I've tried this through Git this time, but it didn't worked in my case.

**Comment by PratyushSingh07** [comment]
then you might as well try to cherry pick but it will be cumbersome

**Comment by utkarsh006** [comment]
> then you might as well try to cherry pick but it will be cumbersome

@PratyushSingh07 Been there, done that. Yes, it's cumbersome, so should I raise a new PR by closing this one?

**Comment by PratyushSingh07** [comment]
sure!!

**Pull request closed without merging**
