### PR TITLE
Added Hindi Translations

### LINKED ISSUE #2366: Required Other Language Translations(Hindi, Kannada, French, etc) for strings which exists in strings.xml (en)
There are many untranslated strings for the Other Languages

app->res->values-es->strings.xml 
This is the main string file for English
Refer to this for the actual strings and translate them to local languages.

Screenshots:

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixes #2366

Added Hindi Translations for the Strings.

Please add #hacktoberfest on merge.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
Please open a PR after you have opened a relevant issue

**Comment by SekhGulamMainuddin** [comment]
> Please open a PR after you have opened a relevant issue

OK I'm adding the issue.

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya please merge my PR

**Comment by PratyushSingh07** [comment]
Re-run the checks

**Comment by SekhGulamMainuddin** [comment]
Hi @therajanmaurya please merge my PR. 
On merge please add **hacktoberfest** tag

**Comment by therajanmaurya** [comment]
Rebase with development and fix the build check

**Pull request closed without merging**
