### PR TITLE
FixIssue#658:Setting emptyView if there is no data

### LINKED ISSUE #658: Setting emptyview if there is no data to display.
**Summary:**

Currently, there is no empty view present in beneficiary and many activities if there is no data to display.It's a good practice to put an empty view if there is no data present. 

**Steps to reproduce:**

Go to Beneficiary Activity ->(If there is any beneficiary delete them all)

**Expected behaviour:**

There should be an empty view present if there is no data.

**Observed behaviour:**

Empty view was absent in different activities.

**Device and Android version:**

Moto G-3(6.0.1).

**Screenshots:**

screenshot_20180220-130921

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #658

Please Add Screenshots If there are any UI changes.
screenshot_20180405-185304

screenshot_20180405-190147

screenshot_20180323-065212

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ivary43** [comment]
@dilpreet96, @droidchef, @therajanmaurya please review.

**Comment by therajanmaurya** [comment]
@ivary43 Please fix the conflicts

**Comment by ivary43** [comment]
@therajanmaurya  done, please review.

**Comment by ivary43** [comment]
@therajanmaurya i have made the changes here please review again.

**Comment by therajanmaurya** [comment]
@ivary43 Please fix the conflicts and we are no longer going add the UI in xml to handle error or No Internet etc. Please use this library: https://github.com/therajanmaurya/Sweet-Error and make changes I will review and merge.

**Comment by ivary43** [comment]
@therajanmaurya  please review this so that we can start adding sweet UI error all over the project.

**Comment by therajanmaurya** [comment]
@ivary43 Please use default icon image if failed to load data and use Beneficiary icon that we are using in navigation drawer if there is no Beneficiary.

**Comment by ivary43** [comment]
@therajanmaurya  done.

**Pull request merged**
