### PR TITLE
Updated dependencies, libs and resolved errors

### LINKED ISSUE #1226: Update library dependencies and build tools, configure build variant
**Summary:**

Update library dependencies and build tools versions to correct and latest ones.
Irradicate sync and build errors + warnings.
Issues with build variant.

**Steps to reproduce:**

Clone the project and build it.

**Expected behaviour:**

The build should be successful without any dependency warnings or errors.

**Observed behaviour:**

Dependency warnings, build tools outdated, build variant issues.

**Device and Android version:**

Android Pi.

 **Issue for GCI**

Beginner level

### PR DESCRIPTION
**Pull request by PiyushSharma99**
Fixes #1226 

libraries

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PiyushSharma99** [comment]
@jddeep @luckyman20 @geekanamika Please review this and approve my submitted task. Thank you!

**Comment by elirehema** [comment]
Hi @PiyushSharma99 make sure you squash your commits

**Comment by PiyushSharma99** [comment]
> Hi @PiyushSharma99 make sure you squash your commits

Yes done!

**Comment by luckyman20** [comment]
@PiyushSharma99 Please fix the travis build.

**Review by jddeep — APPROVED** [review]
Looks good!

**Comment by santoshconflux** [comment]
@PiyushSharma99 , did you mention this PR in the comment section of the GCI ticket and submitted for review?

**Comment by PiyushSharma99** [comment]
@santoshconflux Yes I did. I even updated when comment when I fixed the Travis build. I just saw now that @jddeep approved my task there :). Now can i claim up my next task sir?

**Comment by santoshconflux** [comment]
yes..

**Pull request merged**
