### PR TITLE
refactor: Loan Repayment Schedule

### PR DESCRIPTION
**Pull request by dilpreet2028**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by dilpreet96** [comment]
@therajanmaurya please have a look

**Comment by dilpreet96** [comment]
@therajanmaurya conflicts resolved please have a look at it

**Comment by dilpreet2028** [comment]
@therajanmaurya Please review this PR

**Comment by therajanmaurya** [comment]
@dilpreet96 You have to change the UI in table View as mentioned in Mockup.
image

**Comment by dilpreet2028** [comment]
@therajanmaurya Okay sir :+1:

**Comment by dilpreet2028** [comment]
@therajanmaurya please have a look at it sir

**Comment by therajanmaurya** [comment]
Good Work 👍

**Comment by dilpreet2028** [comment]
Thank you sir :)

**Pull request merged**
