### PR TITLE
fix: removed hardcoded dimens

### LINKED ISSUE #1231: Remove hardcoded dimens from xml layout files
**Summary:**

Remove hardcoded dimen resources from xml layout files. 

**Steps to reproduce:**

Go through the project codebase and layout files.

**Expected behaviour:**

Remove hardcoded dimen resources from xml layout files.

**Observed behaviour:**

Move hardcoded dimension(ex: 10dp) to dimens.xml file

**Device and Android version:**

Android Pi.

**Issue for GCI**

Beginner level.

### PR DESCRIPTION
**Pull request by PiyushSharma99**
Fixes #1231 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PiyushSharma99** [comment]
@santoshconflux @jddeep  Please review and approve asap! Thanks

**Review by jddeep — APPROVED** [review]
:+1:  @PiyushSharma99 Please fix failing builds.

**Review by Sanyam96 — COMMENTED** [review]
lgtm

**Review by ShivangiSingh17 — APPROVED** [review]

**Comment by ShivangiSingh17** [comment]
@PiyushSharma99 close the PR as the issue was already addressed in #1232 and you did the duplication of it. Make sure that you see the already created PRs before working on any issue to avoid duplication.

**Pull request closed without merging**
