### PR TITLE
feat:Change language through settings

### LINKED ISSUE #436: Option to change language from settings
**Summary:**

There should be an option to change language from the app itself

### PR DESCRIPTION
**Pull request by dilpreet2028**
Fixes #436

ss

Please Add Screenshots If any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@dilpreet96 resolve the conflicts.

**Comment by dilpreet2028** [comment]
@therajanmaurya done

**Comment by therajanmaurya** [comment]
@dilpreet96 PR looks good to me, I made many changes can you please pull the code and test and look why app is not working on kitkat.

**Comment by dilpreet2028** [comment]
Okay @therajanmaurya, I will check it and fix it.

**Pull request merged**
