### PR TITLE
fix: extra data in qr share email

### LINKED ISSUE #1133: QR code share creates a useless sendTo address
**Summary:**

When a QR code is shared in loan accounts using E-Mail, it creates the uri of image as the send to address, which should not be present.
**Steps to reproduce:**
Accepted loan -> QR code -> Share using gmail

videotogif_2019 03 19_20 35 47

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #1133 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@therajanmaurya @miPlodder Kindly review.

**Comment by shiv07tiwari** [comment]
@therajanmaurya @miPlodder Fixed the merge conflicts.

**Comment by prashantkh19** [comment]
@shiv07tiwari share the gif of the changes, if possible.

**Comment by prashantkh19** [comment]
@shiv07tiwari share the gif of the changes, if possible.

**Pull request merged**
