### PR TITLE
fix: Crash when QR code shared from loan accounts

### LINKED ISSUE #1117: App crash when QR code shared from loan account
**Summary:**

If QR code shared and back button pressed to return back to the app the the app crashes.

**Steps to reproduce:**

- Click in Accounts
- Click on Loan
- Click on an active Loan Account
- Click on QR code under Monitor

**Expected behaviour:**

App shouldn't crash and should return back to the activity when back button pressed.

**Observed behaviour:**

App crashes when back button pressed.

**Device and Android version:**

Redmi Y2
Android Version 8.1.0

**Relevant GIF**

mifos4

### PR DESCRIPTION
**Pull request by apoorva-mk**
Fixes #1117 

Fixed app crash when QR code shared from loan accounts.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.
 
**GIF**

mifos6

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@apoorva-mk Please follow commit guideline https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide

**Comment by apoorva-mk** [comment]
@therajanmaurya I've made some changes as requested, I'm not quite sure though. Please point out the mistake and I will correct it immediately.

**Comment by therajanmaurya** [comment]
According to commit guideline, your commit message should be `fix: Crash when QR code shared from loan accounts`. Here you can see you should need to add proper prefix whenever you commit.

**Comment by apoorva-mk** [comment]
@therajanmaurya yes I've made the required change. Thanks for pointing it out.

**Comment by prashantkh19** [comment]
@apoorva-mk fix the merge conflicts as soon as you build the project.

**Comment by prashantkh19** [comment]
#1177 fixes this. @therajanmaurya close this

**Pull request closed without merging**
