### PR TITLE
feat: Added animation to tick sign

### LINKED ISSUE #641: Animating the tick icon after transferring money
**Summary:**
When money is transferred from one account to another , a screen of successful transaction comes up which consists of a tick icon . We can animated that icon so as to make a the screen a little more attractive.

**Steps to reproduce:**
Transfer money from one account to another or do a 3rd party transfer.

**Expected behaviour:**
The tick icon can be animated (similar to tick icon in few mobile wallets such as paytm).

@dilpreet96 I would like to add this feature to the app.

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fixes #641 

device-2018-02-18-002517

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by sridharjajoo** [comment]
@therajanmaurya  Please review!

**Comment by therajanmaurya** [comment]
@sridharjajoo Looks good, Please follow commit guideline https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide.

**Comment by sridharjajoo** [comment]
@therajanmaurya Can you tell me what changes do i need to make to this P.R as I am not able to figure out...Thanks :)

**Comment by dilpreet2028** [comment]
@sridharjajoo please change your commit message to: `feat:Added animation to tick sign`

**Comment by sridharjajoo** [comment]
@dilpreet96 Done the changes!Kindly review

**Comment by mohak1712** [comment]
@sridharjajoo You haven't changed the commit message you have changed the title of the PR
you can check `git commit --amend` for reference

**Comment by sridharjajoo** [comment]
@mohak1712 Thanks for the help!

**Comment by sridharjajoo** [comment]
@therajanmaurya Kindly review!

**Pull request merged**
