### PR TITLE
Initial setup for Koin Dependency Inejection

### PR DESCRIPTION
**Pull request by Saifuddin53**
Fixes #Issue_Number

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@AvneetSingh2001 connect with @Saifuddin53 and make sure implementation is following architecture guideline.

**Comment by AvneetSingh2001** [comment]
@Saifuddin53  you have created a new Application class for this?

**Comment by Saifuddin53** [comment]
Yes @AvneetSingh2001 it is necessary for providing the global context for the android application in our kmp (shared) module

**Comment by AvneetSingh2001** [comment]
@therajanmaurya  we can merge this.

**Pull request merged**
