### PR TITLE
chore: Upgraded the version

### LINKED ISSUE #1080: Upgrading the build:gradle version
**Summary:**
Upgrading the gradle version to the latest version helps to access more tools of the application.
The ```build.gradle```  file shows the version to  be 3.0.0 that can be switched to new version 3.3.1 for better interaction and is more stable.

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixes #1080 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by shiv07tiwari — COMMENTED** [review]
@ShivangiSingh17 This issue is already solved in one of the  recent commits

**Comment by ShivangiSingh17** [comment]
@shiv07tiwari which commit, I did not get you?

**Comment by prashantkh19** [comment]
@ShivangiSingh17 This issue is already solved. Can you close this PR?

**Comment by ShivangiSingh17** [comment]
Yes, I will do that.

**Pull request closed without merging**
