### PR TITLE
fix: crash when applying for loan without internet

### LINKED ISSUE #1051: App crashes without internet while Applying for loan
**Summary:**
When the internet is off while clicking on Submit Loan, then App crashes, which should be handled in a graceful manner.
**Steps to reproduce:**

Apply for loan -> Submit loan (Without loan)

**Expected behaviour:**
User should get a message that internet is not available.

**Observed behaviour:**

App crashes.

**Screenshots:**

videotogif_2019 02 19_01 16 12

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #1051 

Please Add Screenshots If there are any UI changes.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
videotogif_2019 02 19_17 50 12
@miPlodder @therajanmaurya Kindly review this PR.

**Comment by miPlodder** [comment]
@shiv07tiwari This will give a good UX, showing empty Spinners. Instead, do a check when the Activity is created and add appropriate error using [Sweet-Error library](https://github.com/therajanmaurya/Sweet-Error)

By this error will also be prevent as no submit button is shown on the screen and the UX will be good.

**Comment by shiv07tiwari** [comment]
@miPlodder What i did in this PR was just to fix the crash without fixing the UI. 
I agree with your approach. I'll make the required Changes.

**Comment by shiv07tiwari** [comment]
@therajanmaurya Fixed the merge conflict.

**Comment by prashantkh19** [comment]
@shiv07tiwari I couldn't find this issue now in the latest build. Could you please check at your end?

**Pull request closed without merging**
