### PR TITLE
feat: workflow to identity stale PR & issues

### PR DESCRIPTION
**Pull request by PratyushSingh07**
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
There are a lot of issues & PRs that remain dormant/unattended to and evidently they accumulate over the years . This yaml file is to make sure that doesn't happen & in the future it will close any PRs/issues that have remained dormant for a long period of time .
For stale issues: it will close the issue if it remains unattended to for 90 days
For stale PRs: It will close the PR if it remains unattended to for 14 days

Do share your thoughts on this @jawidMuhammadi

**Comment by gururani-abhishek** [comment]
> There are a lot of issues & PRs that remain dormant/unattended to and evidently they accumulate over the years . This yaml file is to make sure that doesn't happen & in the future it will close any PRs/issues that have remained dormant for a long period of time . For stale issues: it will close the issue if it remains unattended to for 90 days For stale PRs: It will close the PR if it remains unattended to for 14 days
> 
> Do share your thoughts on this @jawidMuhammadi

I feel that it goes against the spirit of open source. Shutting an issue or PR if it remains unattended for n number of days is not a great metric. After all open source addresses the fact that people come here to code when they find bandwidths out of their regular schedules. I have following pointers, please think about them, 

1. Project Reputation: Enforcing automatic closures without context might make our project appear unfriendly potentially affecting its reputation in the broader open source community.
2. Barrier to New Contributors: For newcomers to the open source community, these strict rules might feel unwelcoming or intimidating. They might hesitate to contribute if they fear their efforts will be dismissed due to time constraints.
3. Quality Over Quantity: It's better to prioritize the quality of contributions over their frequency. By valuing thoughtful and well-implemented contributions, we encourage a culture of excellence and discourage hurried or incomplete work.
4. Inaccurate Metrics: Measuring the health of a project solely based on closure rates can be misleading. It doesn't necessarily reflect the overall engagement, collaboration, or value of the contributions being made.
5. Loss of Expertise: A PR or issue might be opened by someone with specialized knowledge who isn't available to follow up within the specified timeframe. Automatically closing these contributions might result in a loss of their expertise and insights.
6. Complex Problem Solving: Some issues or PRs may involve complex problem-solving that requires more time and collaboration. Rushing to close them after a fixed timeframe could result in missed opportunities for innovative solutions.
7. Diverse Contributors and Schedules: Open source contributors come from various backgrounds and have different schedules. Enforcing rigid time limits may discourage potential contributors who might be busy with other commitments but are still willing to contribute valuable input.
8. Potential for Missed Opportunities: Some issues or PRs might initially seem trivial but could hold significant importance or value in the long term. Automatic closure could mean missing out on these opportunities.
9. Maintainer Responsibility: While automation can streamline processes, maintainers should also take responsibility for managing issues and PRs. Part of maintaining a healthy open source project involves reviewing and triaging contributions, even if it takes time. _**If given the responsibility I'd love to take the responsibility of regularly reviewing new PRs every weekend.**_

**Comment by gururani-abhishek** [comment]
As of PRs are concerned, 30 is not a huge number. Yes, issues require a brush up reviewing and I'd love to pick them up next weekend.

**Comment by PratyushSingh07** [comment]
@gururani-abhishek I think you have entirely misunderstood the workflow , this workflow wont close the issue automatically unless you comment on it. You will be given a warning 7days before its actually closed, you just need to comment on your issues/PR to keep it open ,I hope this answers your 1st & 2nd points

I am not really sure how marking an issues/PR stale leads to any of the points you mentioned between 2 & 9. I will say this again that it wont close the issues automatically , you just need to comment on it to keep it open. The perspective is to eliminate dormant issues . 3 months is a lot of time to follow up with an issue , least someone could expect is to comment on it

As for your last point, we may not have the access to merge any PRs but we can always review PRs voluntarily

**Comment by gururani-abhishek** [comment]
> @gururani-abhishek I think you have entirely misunderstood the workflow , this workflow wont close the issue automatically unless you comment on it. You will be given a warning 7days before its actually closed, you just need to comment on your issues/PR to keep it open ,I hope this answers your 1st & 2nd points
> 
> I am not really sure how marking an issues/PR stale leads to any of the points you mentioned between 2 & 9. I will say this again that it wont close the issues automatically , you just need to comment on it to keep it open. The perspective is to eliminate dormant issues . 3 months is a lot of time to follow up with an issue , least someone could expect is to comment on it
> 
> As for your last point, we may not have the access to merge any PRs but we can always review PRs voluntarily

Marking a PR/issue stale was not really the issue, rather closing it was. After your latest comment certain things are clear. I feel you should mention what will be the criteria to mark a PR/Issue stale in your original comment. That sorta confused me.

**Comment by gururani-abhishek** [comment]
> @gururani-abhishek I think you have entirely misunderstood the workflow , this workflow wont close the issue automatically unless you comment on it. You will be given a warning 7days before its actually closed, you just need to comment on your issues/PR to keep it open ,I hope this answers your 1st & 2nd points
> 
> I am not really sure how marking an issues/PR stale leads to any of the points you mentioned between 2 & 9. I will say this again that it wont close the issues automatically , you just need to comment on it to keep it open. The perspective is to eliminate dormant issues . 3 months is a lot of time to follow up with an issue , least someone could expect is to comment on it
> 
> As for your last point, we may not have the access to merge any PRs but we can always review PRs voluntarily

Plus I've clearly mentioned my points are related to closing an issue/PR on some hard and fast rule, not on marking them stale.

**Comment by PratyushSingh07** [comment]
> Marking a PR/issue stale was not really the issue, rather closing it was. After your latest comment certain things are clear. I feel you should mention what will be the criteria to mark a PR/Issue stale in your original comment. That sorta confused me.

its already mentioned in the workflow @gururani-abhishek  !! 

image

so basically , this is the message you will get on dormant issues, similarly there is another message for PRs

**Comment by jawidMuhammadi** [comment]
Thank you for initiating this PR @PratyushSingh07. In an open-source environment, implementing policies like this can pose challenges and require community-wide agreement. Once agreed upon, these policies should be implemented across all Mifos projects. Have you conducted any research or benchmarking on the approaches you have proposed? It would be helpful to consider the policies that other open-source organizations have in place for PRs and issues on their projects.

**Comment by PratyushSingh07** [comment]
I understand @jawidMuhammadi , I took this idea from other open source projects such as ankidroid and rocket chat. They had this sort of automated mechanism in place which looked really cool if I must say. Also our project in particular has had a history of long standing issue many of which are now dormant or those kind of issues no longer exists. And this was my thought process while creating this PR. 
But as you suggested , I would love to discuss this idea with the community and listen to their POVs

**Pull request closed without merging**
