### PR TITLE
fixed dark mode splash screen.

### LINKED ISSUE #2466: Bug: background color of splash screen doesn't change with theme
**Summary:**

splash screen reamins light mode even in dark mode.

**Expected behaviour:**

it should be in dark mode if the app is in dark mode

**Screenshots:**
[Screen_recording_20240101_222318.webm](https://github.com/openMF/mifos-mobile/assets/136256522/0b74c53a-9901-4755-9b55-59602c473851)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

### PR DESCRIPTION
**Pull request by KUSHAL-RAJ-PAREEK**
@PratyushSingh07 
Fixes #2466

https://github.com/openMF/mifos-mobile/assets/115624967/4b077ecd-bd14-47d0-87d2-3150bfdf3b15

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
alright @KUSHAL-RAJ-PAREEK 3 things that I would like to point out :
- Maan sharma was supposed to open the PR first and he had even commented on the issue before you opened this PR yet you decided to go ahead with it
- you havent followed the contribution guidelines. (Always go through the README.md and CONTRIBUTING.md of any repo before you raise a PR) and lastly
- have you checked your changes against the light theme ? (i think that splash screen has now been set to always follow dark theme)

I appreciate the enthusiasm, but it's crucial to uphold the essence of open source. Don't limit your contributions solely with GSoC in mind. Take the time to learn from fellow contributors, and, most importantly, avoid rushing the process. I hope you will not repeat this

**Comment by KUSHAL-RAJ-PAREEK** [comment]
@PratyushSingh07 
but it is working:-

https://github.com/openMF/mifos-mobile/assets/115624967/e1cb28aa-af3e-40d5-bf8c-5d3166601dd4

**Comment by KUSHAL-RAJ-PAREEK** [comment]
so, if i follow quidelines then i also cant able to make pr?

**Comment by KUSHAL-RAJ-PAREEK** [comment]
guidelines file for pr in readme is not found.

**Comment by PratyushSingh07** [comment]
Why won't you be able to make a PR if you follow the guidelines? You have taken my points out of context. 

Also you are changing the system theme. Try changing the theme from inside of the app to see if it works

**Comment by PratyushSingh07** [comment]
> guidelines file for pr in readme is not found.

Did you try checking contributing.md ??

**Comment by KUSHAL-RAJ-PAREEK** [comment]
i am saying that pr guidelines link is not working.

**Comment by KUSHAL-RAJ-PAREEK** [comment]
ok i go it. thanks

**Comment by KUSHAL-RAJ-PAREEK** [comment]
i am trying to register in app but it saying unable to register.
is there any dummy id and password.

**Comment by KUSHAL-RAJ-PAREEK** [comment]
ya its not changing let me see.

**Comment by KUSHAL-RAJ-PAREEK** [comment]
@PratyushSingh07 sir i am tried a lot but can't able to solve can you please tell me hoe this thing resolve

**Comment by PratyushSingh07** [comment]
do you still plan to solve the issue in this PR or should I close it @KUSHAL-RAJ-PAREEK ?

**Comment by KUSHAL-RAJ-PAREEK** [comment]
@PratyushSingh07 i will spend some more time on this issue.

**Comment by PratyushSingh07** [comment]
I am converting this PR to draft

**Comment by PratyushSingh07** [comment]
closing due to inactivity. Reopen the PR if you make any progress

**Pull request closed without merging**
