### PR TITLE
fix:Opens phone dialer on clicking the helpLine number

### LINKED ISSUE #515: Clicking on HelpLine number doesn't do anything
**Summary:**

Clicking on HelpLine number should open the phone dialer on home screen

### PR DESCRIPTION
**Pull request by Rish02Sharma**
Fixes #515 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Rish02Sharma** [comment]
@therajanmaurya @dilpreet96 Please review.

**Comment by therajanmaurya** [comment]
@Rish02Sharma I think `android:autoLink="phone"` will solve the issue. Please check.

**Comment by Rish02Sharma** [comment]
@therajanmaurya Sorry for a late response......have tried android:autoLink="phone" but it is not solving this issue...i think we have to do it by the intent method only....please tell if i am wrong.

**Comment by dilpreet2028** [comment]
@Rish02Sharma Have a look at this link: https://stackoverflow.com/questions/40788608/androidautolink-for-phone-numbers-doesnt-always-work

**Comment by Rish02Sharma** [comment]
@therajanmaurya @dilpreet96 Yeah it's done now! 👍

**Pull request merged**
