### PR TITLE
fix: It will now show an error message for invalid phone numbers.

### PR DESCRIPTION
**Pull request by itsPronay**
image

A phone number is invalid if it contains anything other than numbers

Please make sure these boxes are checked before submitting your pull request - thanks!
- [ ] Apply the AndroidStyle.xml style template to your code in Android Studio.
- [ ] Run the unit tests with ./gradlew check to make sure you didn't break anything
- [ ]  If you have multiple commits please combine them into one commit by squashing them

### CODE REVIEW

**Comment by itsPronay** [comment]
wondering why it failed

**Comment by itsPronay** [comment]
./gradlew check

**Comment by itsPronay** [comment]
@therajanmaurya hello, could you please review this PR?

**Comment by PratyushSingh07** [comment]
Dont worry about the failing checks @itsPronay.

**Comment by PratyushSingh07** [comment]
Please follow the commit guidelines and squash your commits into one @itsPronay

**Comment by itsPronay** [comment]
ok ... I will be sending another PR then. I am closing this one since it has 2 commits

**Pull request closed without merging**
