### PR TITLE
fix : DatePicker UI changes in Open Saving Account Transaction screen

### LINKED ISSUE #623: DatePicker UI in open saving account transaction screen
**Summary:**

Date Picker in Saving Account Transaction screen is not good UI/UX

**Steps to reproduce:**

Open Saving Account Transaction Screen -> Pick a date

**Expected behaviour:**

There should be a uniform color throughout and the size of the picker should be correct

**Observed behaviour:**

There is a clearly visible white patch and the picker looks a bit stretched than a usual DatePicker

**Device and Android version:**

LeEco2(6.0)

**Screenshots:**

error

I would like to work on this

### PR DESCRIPTION
**Pull request by mohak1712**
Fixes #623 

fix

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mohak1712** [comment]
@dilpreet96 @therajanmaurya Please review this PR.

**Comment by therajanmaurya** [comment]
@mohak1712 did you tested this in 7.0 devices. Please do and let me know It is working fine.

**Comment by mohak1712** [comment]
Sure i will check this and let you know

**Comment by mohak1712** [comment]
@therajanmaurya - looks good
OnePlus5(8.0)

whatsapp image 2018-03-21 at 13 12 42

**Comment by therajanmaurya** [comment]
@mohak1712 Please see we can't see the `ok` and `cancel` button it have white background.

**Comment by mohak1712** [comment]
@therajanmauryaI have made the changes, please check

OnePlus5T(8.0)
whatsapp image 2018-03-22 at 22 31 29

LeEco2(6.0)
whatsapp image 2018-03-22 at 22 29 44

**Pull request merged**
