### PR TITLE
Added message for error 401 "Invalid username or password" in all lan…

### LINKED ISSUE #1986: Toast message in case of wrong credentials
**Summary:**

If a user enters a wrong username or password then currently the toast being displayed is `Inavalid authentication details passed in api request` . I believe this should be changed to something more meaningful to the user such as `Incorrect username or password ` or  `Unable to authenticate user`

**Steps to reproduce:**

- enter either a wrong username or a wrong password at the time of login

**Device and Android version:**
Device : Samsung M11
Android : 11

**Screenshots:**
<table>
 <tr>
 <td></td>
</table>

### PR DESCRIPTION
**Pull request by RobustMj**
**Added a message for error 401 "Invalid username or password" in all languages and its not hardcoded**

Fixes #1986 

Screenshot_20230324_181416

**In different language**   
__To check this you have to reopen the app after language change because logout bug fix #2002  will be merged later __  

Screenshot_20230324_181550

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RobustMj** [comment]
@jawidMuhammadi Sorry for taking soo much time for creating this PR i had many issues as this was my 1st PR, please look into this.

**Comment by RobustMj** [comment]
@jawidMuhammadi here

**Comment by RobustMj** [comment]
@jawidMuhammadi When this PR will be merged ?

**Comment by jawidMuhammadi** [comment]
This PR doesn't implement fully what has been discussed in the mentioned issue, and also you have not followed any coding standards including our commit and pull request template styles. Unfortunately, we can't accept this PR :(

**Comment by RobustMj** [comment]
> This PR doesn't implement fully what has been discussed in the mentioned issue, and also you have not followed any coding standards including our commit and pull request template styles. Unfortunately, we can't accept this PR :(

I think I may have missed this "When the login button is clicked, then hide the keyboard" but I don't think it requires progress bar because it hardly takes 2 secs and idk what coding standards you mentioned , I did used AndroidStyle template.

**Comment by kingbass01** [comment]
@RobustMj He means to say to follow Pull Request Guidelines mentioned here https://github.com/openMF/mifos-mobile/blob/development/.github/CONTRIBUTING.md#pull-requests which includes squashing your commits to one commit and follow commit message and Pull Request Title guidelines which you didn't follow

**Pull request closed without merging**
