### PR TITLE
feat: set whole app to work only in portrait mode

### LINKED ISSUE #998: Setting app to work only in Portrait Mode
**Summary:**

The app has many bugs when working in landscape mode and also on device rotation. It will be better if we restrict all activities to work in portrait mode only.
This would solve many small bugs throughout the app.

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #998 #992 #1103 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by RajaVamsi11 — COMMENTED** [review]
@shiv07tiwari Please fix the Travis build

**Comment by shiv07tiwari** [comment]
@therajanmaurya @miPlodder I am unable to identify the exact error for Travis. Can I please get some help.

**Comment by shiv07tiwari** [comment]
@therajanmaurya @miPlodder Fixed the build

**Comment by shiv07tiwari** [comment]
@therajanmaurya @miPlodder Solved the merge conflict.

**Comment by therajanmaurya** [comment]
This is not a good idea, We have a future plan to add tablet UI. and better we are going to add jetpack that will solve all the issue of device rotation.

So I am closing it.

**Pull request closed without merging**
