### PR TITLE
Changes In new Login page

### PR DESCRIPTION
**Pull request by CodyHarsh**
Fixes #Issue_Number

Please Add Screenshots If there are any UI changes.
Screenshot_2021-01-06-22-21-18-10_0b55964ac4df2babebf0d80487f8a230
Screenshot_2021-01-06-22-21-31-04

Please make sure these boxes are checked before submitting your pull request - thanks!

### CODE REVIEW

**Comment by CodyHarsh** [comment]
Here I have given the UI changes.

**Review by PatelVatsalB21 — COMMENTED** [review]
@CodyHarsh please check for error before commit using `.\gradlew check --scan` in terminal.

**Comment by CodyHarsh** [comment]
> @CodyHarsh please check for error before commit using `.\gradlew check --scan` in terminal.

I have done that can you help me out by doing this for me because I cannot solve that error

**Comment by CodyHarsh** [comment]
@butterknife.BindView()
    ^

> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

**Comment by garvit984** [comment]
@CodyHarsh This PR is not in accordance with the contributing guidelines.

**Pull request closed without merging**
