### PR TITLE
fix: nav drawer item update

### PR DESCRIPTION
**Pull request by dilpreet2028**
Fix for #262 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by dilpreet2028** [comment]
@therajanmaurya please have a look at this

**Comment by therajanmaurya** [comment]
@dilpreet96 Please fix the conflicts.

**Comment by dilpreet96** [comment]
@therajanmaurya conflicts fixed and someone has changed for selfservice to "password"

**Comment by dilpreet96** [comment]
Conflicts resolved @therajanmaurya @puneetkohli521

**Comment by dilpreet96** [comment]
@therajanmaurya conflicts fixed

**Comment by dilpreet2028** [comment]
@therajanmaurya PR updated.

**Pull request merged**
