### PR TITLE
fix:show message on failing to load loan template

### LINKED ISSUE #299: Show message and retry button if app failed to fetch LoanTemplate while applying for loan
**Summary:**

In Present we are fetching the loan template and inflating into the UI content but if app failed to fetch the loan template. It's can make app crash or HTTP request failure reason. It's better to show a **message and retry** button if app failed to fetch loan template.

**Steps to reproduce:**

Try to apply loan application without internet connection. App is crashinng.

**Expected behavior:**

It should show the message and retry button at the centre of screen

**Observed behavior:**

It showing empty UI and on click apply loan. Application is crashing.

**Device and Android version:**

MOTO G Turbo 3

### PR DESCRIPTION
**Pull request by dilpreet2028**
Fixes #299 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@dilpreet96 This is not a good approach. 
Please read again the `Expected behavior` in issue message. 
Let me know if you need any help. we can schedule hangout call.

**Comment by dilpreet96** [comment]
@therajanmaurya changes made accordingly

**Comment by dilpreet2028** [comment]
@therajanmaurya made changes accordingly

**Comment by therajanmaurya** [comment]
This is good for now. Let's discuss tomorrow about the project.

**Comment by dilpreet2028** [comment]
Okay @therajanmaurya

**Pull request merged**
