### PR TITLE
feat: AccountsPresenter Test

### PR DESCRIPTION
**Pull request by dilpreet2028**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@dilpreet96 good work, while adding json file, if json is list type then you should add only two object in list.

**Comment by dilpreet2028** [comment]
@therajanmaurya I added 3 or 4 objects for each type as earilier file were beyond 2k lines. Should I reduce it more?

**Comment by therajanmaurya** [comment]
Add max 3 object only that is sufficient for testing.

**Comment by dilpreet2028** [comment]
Just checked SavingsObject in both file contains 3 objects, Loan objects contains 3 objects, Share object contains 2 objects

**Comment by therajanmaurya** [comment]
I know you added 3 objects, I am letting you know that you should follow this thing for future.

**Comment by dilpreet2028** [comment]
Okay @therajanmaurya , I will make sure no more than 3 objects are added in future

**Comment by therajanmaurya** [comment]
I am adding this PR for now. send a PR in which our travis should run the instrumentation test too.

**Comment by therajanmaurya** [comment]
So I know your test is passing.

**Comment by dilpreet2028** [comment]
Okay I will do it.

**Pull request merged**
