### PR TITLE
Fix #661 : Wrong Passcode Dot Issue

### LINKED ISSUE #661: Bug while entering the passcode
**Summary:**
When the wrong passcode is entered in the passcodeview , the 4th dot isn't visible which doesn't occur when correct passcode is entered.

**Steps to reproduce:**
Enter the wrong passcode in passcodeview.

**Expected behaviour:**
The 4th dot should also be visible and then the snackbar should appear that the passcode is wrong.

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #661 

pr_passcode

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@therajanmaurya Please review this PR.

**Comment by therajanmaurya** [comment]
@miPlodder send this PR in Passcode library repo and use the library here too.

**Comment by miPlodder** [comment]
@therajanmaurya Ok

**Comment by therajanmaurya** [comment]
or wait, Let me give this task to @dilpreet96 he can finish this task with in hour, he know everything. you can carry on with your task.

**Comment by miPlodder** [comment]
@therajanmaurya Ok

**Comment by therajanmaurya** [comment]
@miPlodder  please make this PR in the library project I will merge it.

**Comment by miPlodder** [comment]
@therajanmaurya I will do that.

**Comment by miPlodder** [comment]
@therajanmaurya I have created PR (https://github.com/openMF/mifos-passcode/pull/14) in library.

**Comment by prashantkh19** [comment]
@therajanmaurya We have this PR in the library project. We can close this from here.

**Pull request closed without merging**
