### PR TITLE
fix: #1024 Scrolling is working in landscape mode also

### LINKED ISSUE #1024: Scroll function is not available on screen rotation
**Summary:**
On screen rotation in Add Beneficiary section the scroll option is not available and the screen is just set to some limited options.

**Steps to reproduce:**
1. From Home screen, click on ```Beneficiaries``` 
1. Click on Fab option.
1. Enable screen rotation.

**Expected behaviour:**
 On screen rotation in Add Beneficiary section all the select mode options **Add**, **Scan** and **Upload QR** should be available.

**Observed behaviour:**
On changing orientation only **Add** and **Scan** options are seen on the screen.

**Device and Android version:**

Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Screenshots:**
noscroll

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixes #1024 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ShivangiSingh17** [comment]
@therajanmaurya can you please review this PR.

**Review by shiv07tiwari — COMMENTED** [review]
@ShivangiSingh17 Their was a community discussion in which it was concluded that the app should work only in portrait mode.
So this issue will be solved along side that issue.

**Comment by prashantkh19** [comment]
@ShivangiSingh17 as per the community discussions, we are restricting the app to work in portrait mode only. 
Ideally, you should start working on an issue after maintainers give you a green signal, otherwise, a lot of time and code is wasted for no use.

**Comment by prashantkh19** [comment]
can you close this PR?

**Comment by ShivangiSingh17** [comment]
ya sure @prashantkh19

**Pull request closed without merging**
