### PR TITLE
chore: Update branch policy

### PR DESCRIPTION
**Pull request by ashwinkey04**
Revert to old branch policy post the finalization of Kotlin migration PR

### CODE REVIEW

**Comment by miPlodder** [comment]
Can we update the commit type with `docs`, instead of `chore`

**Review by miPlodder — CHANGES_REQUESTED** [review]
Can we update the commit type with `docs`, instead of `chore` in the commit-msg?

One suggestion for local development, which might help you, use the below convention for branch naming,

`<commitType>#<issueId>_<some-msg-specific-to-do-changes>`
for instance, `feature#123_update_readme_branch_policy`

Also, add an `issue id` in the commit-msg. (Create an issue for these changes with description and use it in the commit-msg). This will ensure good sustainability in the long run.
`<commitType>#<issueId>: <commit-msg>`
for instance, `docs#123: updated branch policy in readme`

**Comment by miPlodder** [comment]
@ashwinkey04 Can you address the review comment, so that I can merge it.

**Comment by ashwinkey04** [comment]
> @ashwinkey04 Can you address the review comment, so that I can merge it.

Changes done

**Pull request merged**
