### PR TITLE
Shift account balance to top in savings loan detail

### LINKED ISSUE #473: Give preference to Account Balance shown in Savings and Loan Account Details
**Summary:**

Account Balance shown in Savings and Loan Account Details should be given more preference than other things shown.

 
Shift Account Balance to the top and increase it's size and make the amount bold.

### PR DESCRIPTION
**Pull request by mofetej**
Fixes #473 

Please Add Screenshots If any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
@mofetej Please close this PR as this issue is already resolved by me

**Comment by therajanmaurya** [comment]
Hi @luckyman20, I know very well. It's come under project management and GCI is going on. So I will suggest concentrate on task and leave these things to us. It does not mean somebody did the same thing by mistake that does not mean that his effort will not count.  
Best of luck both @mofetej, @luckyman20  for GCI

**Comment by luckyman20** [comment]
@therajanmaurya and @mofetej Sorry, I didn't mean to hurt somebody by saying that your efforts are useless. Instead, I was saying check the issue first and see whether the issue is resolved by somebody else or not. In this method, if someone have already resolved the issue you don't have to resolve it again. It is very painful when you do some work and it goes countless.

**Comment by therajanmaurya** [comment]
As @luckyman20 mentioned that this PR already resolved. So I am closing this PR. 
@mofetej Your work is really good Best of luck for future.

**Pull request closed without merging**
