### PR TITLE
docs: Correct repo name

### PR DESCRIPTION
**Pull request by Sagar0-0**
Correct the repo name in the "Building the code" section in README.md.

### CODE REVIEW

**Comment by jawidMuhammadi** [comment]
Please follow the [Commit Style](https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide) and [Pull Request ](https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide)Guidelines.

**Comment by Sagar0-0** [comment]
No dedicated issue was created for this minor change. So, should I create one or just modify the commit name?

**Comment by jawidMuhammadi** [comment]
Modifying the PR name should be enough for this one.

**Comment by Sagar0-0** [comment]
Done

**Pull request merged**
