### PR TITLE
Fixed #897 - Username is shown as "null" on Login

### LINKED ISSUE #897: Username is shown as "null" on login
**Summary:**

Username is shown as "null" on login

**Steps to reproduce:**

Login to app

**Expected behaviour:**

Username should be shown

**Observed behaviour:**

Username is shown as null

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by e-qui-nox**
Fixes #897

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@e-qui-nox This is a temporary fix, not a permanent solution. You are just passing the username entered during login.

**Comment by e-qui-nox** [comment]
The username enter during login should be shown rgt?

**Comment by e-qui-nox** [comment]
The username entered during login should be shown right?

**Comment by miPlodder** [comment]
@e-qui-nox Check why it's showing a non-null response from the API as a null response.

**Pull request closed without merging**
