### PR TITLE
Updated kotlin version

### LINKED ISSUE #1194: #API variant
API 'variant.getPreBuild()' is obsolete and has been replaced with 'variant.getPreBuildProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPreBuild(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixes #1194 
Upgraded kotlin version to the most recent and stable version.

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@ShivangiSingh17 I guess we have the bot for dependency upgradation:)

**Comment by ShivangiSingh17** [comment]
@Bhavnaharitsa yeah we do have the dependency bot for upgradations but I didn't see any PR regarding the same yet. Let me know if any of the PR created by the dependency bot regarding the same exists.

**Comment by Bhavnaharitsa** [comment]
@ShivangiSingh17 Sure thing Shivangi, don't worry :) But I think for now, you can close this as you've come to know about it

**Comment by ShivangiSingh17** [comment]
It is a sure thing and I am keeping on it. I know about it well as I suggested this bot implementation but it seems to miss out on some important updates.

**Pull request closed without merging**
