### PR TITLE
Fix: Fixed date picker limits in Apply for Loan Section

### LINKED ISSUE #560: Date picker not working properly in Apply for Loan section.
**Summary:**

Unable to select future dates in expected disbursement date in apply for loan section.

**Steps to reproduce:**

Open the app->Apply for loan ->click on expected disbursement date. 

**Expected behaviour:**

Since expected disbursement date is the date till what we want our loan money, so it should be any future date but we can't select a future date in the app.
  
**Observed behaviour:**
Unable to select the future date for expected disbursement date.

**Device and Android version:**

Device: Moto G-3.
Android Version: 6.0.1.

**Screenshots:**

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #560

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ivary43** [comment]
@dilpreet96, @therajanmaurya  please review.

**Comment by dilpreet2028** [comment]
@ivary43 can you rebase your branch with the latest code and test again.

**Comment by ivary43** [comment]
@dilpreet96  yes i am facing the same issue now too.

**Comment by ivary43** [comment]
@dilpreet96 I think problem is with this line 
https://github.com/openMF/mifos-mobile/blob/development/app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java#L53-L55
we are not setting the value of  ```isStartOrEnd``` through the constructor.

**Comment by therajanmaurya** [comment]
Please fix conflicts.

**Comment by ivary43** [comment]
@therajanmaurya done, please review again.

**Comment by ivary43** [comment]
@therajanmaurya this issue is still present can you please review it.

**Comment by miPlodder** [comment]
Already Fixed #912

**Pull request closed without merging**
