### PR TITLE
feat:added Qr import functionality to add beneficiary

### LINKED ISSUE #842: Allow user to import QR Code from gallery for adding a Beneficiary
**Details :**

User can import the QR Code from the gallery. To implement this functionality, User will have
to adjust the QR Code and put it inside the box either by Zooming (In/Out) or by moving the
image. When the User has adjusted the image, he/she can press the Scan Button to proceed, or
Cancel Button if he/she doesn’t want to scan the QR Code.
After successful scan, Add Beneficiary form will be displayed, whereas if the scan fails, we will
inform the User via message.

**Mockups :** 

image

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #842

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ivary43** [comment]
@therajanmaurya please review.  I have used [this](https://github.com/igreenwood/SimpleCropView) this has MIT license.

**Comment by therajanmaurya** [comment]
I did not investigate but I think we are using this library (https://github.com/zxing/zxing) and this library should be reading qr code from image

**Comment by ivary43** [comment]
@therajanmaurya I am using zxing library look in the presenter ..but it can't process the whole the image if we pass the whole image ...so we have to crop it to the barcode region only and still use flags and hints to find it

**Comment by therajanmaurya** [comment]
Ok then please fix the conflicts

**Comment by ivary43** [comment]
@therajanmaurya  done please review again

**Pull request merged**
