### PR TITLE
chore: #1861 Update dependencies versions and make necessary changes afterwards

### LINKED ISSUE #1861: Update dependencies versions and make neccessary changes afterwards
To use the android libraries which are not added as dependencies in the app right now(e.g. constraint layout), We'll have to find the version of the library which is compatible with the libraries included in the app. 

## Why
Because latest version of the new dependencies introduces latest version of other libraries like core-ktx and app-compat as transitive dependencies which require updating Gradle and Kotlin versions and updating the compileSdk of the app.

### PR DESCRIPTION
**Pull request by Maan-Sharma**
Fixes #1861
*Dependency Updates:
Updated testing dependencies, including JUnit, Mockito Core, Mockito Android, Espresso-contrib, and androidx.annotation, to their specified versions.
Upgraded the Hilt library to version 2.50.
Updated various other dependencies in the project, such as Dagger Hilt, Kotlin, support libraries, Firebase, and Android Gradle Plugin.

*Code Modifications:
Improved MediaType creation in RetrofitUtils.kt using the toMediaTypeOrNull extension function.
Enhanced header handling in SelfServiceInterceptor.kt by using toString() for token and tenant values.
Improved MediaType creation in GuarantorRepositoryImp.kt using the toMediaTypeOrNull extension function.
Made adjustments in HomeActivity.kt related to error dialog display for Play Services.
Enhanced map initialization in LocationsFragment.kt using MapsInitializer.

*Gradle File Updates:
Updated various versions in the project's build.gradle, including support libraries, Dagger Hilt, Kotlin, JUnit, Mockito, Espresso, and others.

*Notes:
Thoroughly test the application to ensure compatibility and stability.
Keep track of the changes for documentation and future reference.
These changes aim to enhance the project by adopting newer versions of dependencies, improving code readability, and ensuring compatibility across libraries.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
follow our [contribution](https://github.com/openMF/mifos-mobile/blob/development/.github/CONTRIBUTING.md) guidelines @Maan-Sharma

**Comment by Maan-Sharma** [comment]
I need to follow this? @PratyushSingh07 
Summary: Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
Steps to reproduce: How can we reproduce the issue?
Expected behavior: What did you expect the app to do?
Observed behavior: What did you see instead? Describe your issue in detail here.
Device and Android version: What make and model device (e.g., Samsung Galaxy S3) did you encounter this on? What Android version (e.g., Android 4.0 Ice Cream Sandwich) are you running? Is it the stock version from the manufacturer or a custom ROM?
Screenshots: Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.
Possible fixes: If you can, link to the line of code that might be responsible for the problem.

**Comment by Maan-Sharma** [comment]
@PratyushSingh07  is anything wrong in code? 
or my way ? that how, I make PR

**Comment by Maan-Sharma** [comment]
@PratyushSingh07   I am so sorry ,I didn't write any summary. Have I make PR again or what i do next?

**Comment by PratyushSingh07** [comment]
well to edit PR description you can simply click on the 3 horizontals dots . But to change the commit message you will have to use git commit --amend command. For more details refer this [1](https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages) or [2](https://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote)

Both the links are essentially the same , there is just a slight variation : )

**Comment by Maan-Sharma** [comment]
@PratyushSingh07 sir, hava a look on PR description.

**Comment by PratyushSingh07** [comment]
PR description is decent, change the commit message as well and then I'll approve your PR 

Also don't call me sir . Pratyush is just fine

**Comment by Maan-Sharma** [comment]
@PratyushSingh07 
now it is ok?

**Comment by PratyushSingh07** [comment]
Yeah the message is fine but now you will have to merge your commits into one

**Comment by Maan-Sharma** [comment]
@PratyushSingh07  in my device is build successfully then why Some checks were not successful

**Comment by Maan-Sharma** [comment]
Screenshot 2024-01-03 232457

**Comment by Maan-Sharma** [comment]
@PratyushSingh07  can i make this pr again , its soo messed now

**Comment by PratyushSingh07** [comment]
Yes you can open another PR. However I feel that updating any dependency right now isn't feasible. Updating a Dependency may start a chain reaction and before you realize you may end up changing a whole lot of code which in my opinion is never ideal. 

As a developer I think we should update any dependencies only when needed. This was another reason that provoked us to discontinue the dependabot and renovate bot.

**Comment by Maan-Sharma** [comment]
ok then

**Pull request closed without merging**
