### PR TITLE
Fix Syntax Errors and Improve Unit Test Coverage

### LINKED ISSUE #2527: Refactor: Unit Test Syntax Errors and Failures
**Summary:**

The unit tests in the Android project contain syntax errors, due to this , we cannot run any test and add the new one .
We cannot execute `./gradlew check ` while raising PR too . 

**Steps to reproduce:**

1. Navigate to the test directory 
2. Open any of the test files .
3. Attempt to run any unit test 

**Expected behaviour:**

No syntax error and unit test running 

**Observed behaviour:**

 Encountered the syntax error on the multiple files . Felt the necessity to rewrite them . 
**Device and Android version:**
Android studio 

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by NiranjanNlc**
Fixes #2527 

 In this pull request, I address the syntax errors present in some of unit test files and improve the  est coverage of the Android project . 
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by NiranjanNlc** [comment]
Hi @PratyushSingh07 and @therajanmaurya  ,
Please just review this PR. 
since, i need to rewrite some of the approach , i just want to validate from you people that every thing is upto par .

Under approval of yours , i will apply these in other classes too . 
Thanks

**Comment by PratyushSingh07** [comment]
I believe you should probably use turbine to write unit tests as we are using kotlin flows

**Comment by NiranjanNlc** [comment]
> I believe you should probably use turbine to write unit tests as we are using kotlin flows

Thanks @PratyushSingh07  for suggestion.

**Comment by NiranjanNlc** [comment]
hey @PratyushSingh07 ,
I have used the turbine  for testing flow .

Any feedback from your side ??

**Comment by therajanmaurya** [comment]
I can see you have deleted so many ViewModel unit test why?

**Comment by NiranjanNlc** [comment]
> I can see you have deleted so many ViewModel unit test why?

I just want to make sure the  approach i followed now is upto par . 
I will add them if you validate this approach . 
Shall i go with these approach now ? 
You can merge PR after i added all of them .
Thanks .

**Comment by NiranjanNlc** [comment]
> I can see you have deleted so many ViewModel unit test why?

hey @therajanmaurya ,
I have added all of the test files for now .
and all of the test are passed .
Please get it reviewed now thanks

**Review by therajanmaurya — APPROVED** [review]

**Pull request merged**
