### PR TITLE
refractor: Migration of update password screen to compose

### LINKED ISSUE #2561: Refactor: Migration of update password screen (XML to compose)

### PR DESCRIPTION
**Pull request by itsPronay**
fixes : #2561

Compose 
image

screen recording - 
[Screencast_04_07_2024_04:29:57_AM.webm](https://github.com/openMF/mifos-mobile/assets/78101731/3830a9f3-d500-4935-8c48-dce98663edc1)

### CODE REVIEW

**Comment by AvneetSingh2001** [comment]
@itsPronay can you please edit your commit message to follow the commit guidelines.  
Also ideally we should implement the whole screen in compose, So please make use of Topbar and ProgressIndicator of Compose rather than using the old way.

**Comment by itsPronay** [comment]
@AvneetSingh2001 Okay!

**Comment by itsPronay** [comment]
@AvneetSingh2001 Please take a look at my code and let me know if I should make any changes in it

**Comment by AvneetSingh2001** [comment]
I see you still have not used compose progress indicator. Also you need to collect the flows as state in the compose itself. please go through my recent [PR](https://github.com/openMF/mifos-mobile/pull/2563) for the reference. 
Also me are aiming to eradicate fragments in the future, so migrate code in such a way that fragments should only be use return compose view.

**Comment by itsPronay** [comment]
@AvneetSingh2001 Okay bro! thanks for reviewing. I will make the necessary changes ASAP

**Comment by itsPronay** [comment]
I am really sorry. I have to close this one as it created conflicts + my git is now pretty messed up right now. I will be raising a new PR. Sorry about that...

**Pull request closed without merging**
