### PR TITLE
Updated filter in SavingAccountsTransactionFragment

### LINKED ISSUE #735: feature:add filters for deposit and withdrawal  in savings account transaction section
**Summary:**
In savings account transactions the list is too long for some account.So it would be better if we add a filter for withdrawal and deposit, it would be much easier go through the transactions.

**Screenshots**
screenshot_20180314-232927

### PR DESCRIPTION
**Pull request by prashantkh19**
Fixes #735 #1096 
### **Screenshots**
image
image

### CODE REVIEW

**Review by zoman-anamika — APPROVED** [review]
Looks good to me. Good work :)

**Review by geekanamika — COMMENTED** [review]
As a suggestion, You can Open filter dialog as full-screen dialog instead of pop-up dialog. :)

**Comment by prashantkh19** [comment]
> As a suggestion, You can Open filter dialog as full-screen dialog instead of pop-up dialog. :)

Yeah, but that won't be consistent with the other filter dialogs.

**Comment by geekanamika** [comment]
> > As a suggestion, You can Open filter dialog as full-screen dialog instead of pop-up dialog. :)
> 
> Yeah, but that won't be consistent with the other filter dialogs.

Agreed. We can work on it if we'll think about UI revamp. Replacing pop-up dialogs with Bottom sheet or full screen dialogs depending upon use-case :)

**Pull request merged**
