### PR TITLE
Fixed: #2395 Added SDK Checks for Deprecated Parcelable and Serializable Functions

### LINKED ISSUE #2395: Add SDK Checks to Deprecated Parcelable and Serializable functions
**Summary:**

Since API Level 33 (TIRAMISU), many Parcelable and Serializable functions have been deprecated
Ex- getSerializable(key), getParcelable(key), getParcelableArrayList(key)
These are to be replaced by adding SDK checks-

**For ParcelabeArrayList**
Previous - 
```
val result : List<YourParcelableClass> = <YourBundle>.getParcelableArrayList(key)
```
To - 
```
val result : List<YourParcelableClass> = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        <YourBundle>.getParcelableArrayList(key,  <YourParcelableClass>::class.java)
    } else {
         <YourBundle>.getParcelableArrayList(key)
    }
```

**For Parcelabe**
Previous - 
```
val result : YourParcelableClass = <YourBundle>.getParcelable(key)
```
To - 
```
val result : YourParcelableClass = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        <YourBundle>.getParcelable(key,  <YourParcelableClass>::class.java)
    } else {
        <YourBundle>.getParcelable(key)
    }
```

**For Serializable**
Previous - 
```
val result : YourSerializableClass = <YourBundle>.getSerializable(key)
```
To - 
```
val result : YourSerializableClass = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        <YourBundle>.getSerializable(key,  <YourSerializableClass>::class.java)
    } else {
        <YourBundle>.getSerializable(key) as YourSerializableClass
    }
```

Also, add null checks in order to be safe from NullPointerException

Where To Add These Changes:
You can find it in the Activity Classes present in folder - \mifos-mobile\app\src\main\java\org\mifos\mobile\ui\activities
and Fragment Classes present in folder - \mifos-mobile\app\src\main\java\org\mifos\mobile\ui\fragments

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixes: #2395 

Added SDK Checks for the Deprecated Parcelable and Serializable Functions.

Made an Object Class ParcelableAndSerializableUtils to do all the work so as to reduce redundancy in the code and refactored the activities and fragments containing the deprecated  Parcelable and Serializable Functions.

```
object ParcelableAndSerializableUtils {

    fun <T> Bundle.getCheckedArrayListFromParcelable(classType: Class<T>, key: String): List<T>? {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            this.getParcelableArrayList(key, classType)
        } else {
            this.getParcelableArrayList(key)
        }
    }

    fun <T> Bundle.getCheckedParcelable(classType: Class<T>, key: String): T? {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            this.getParcelable(key, classType)
        } else {
            this.getParcelable(key)
        }
    }

    fun <T : Serializable> Bundle.getCheckedSerializable(classType: Class<T>, key: String): Any? {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            this.getSerializable(key, classType)
        } else {
            this.getSerializable(key)
        }
    }

}
```

### CODE REVIEW

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 can you please review my PR

**Comment by PratyushSingh07** [comment]
I don't think of it as a priority as we are in the midst of migration. We can avoid this easily if we use navigation graph ( safe args should be enough imo). And in the future we are looking to entirely migrate the project to compose and it such a case we wouldn't really have to worry about this warning

**Comment by therajanmaurya** [comment]
Hi @SekhGulamMainuddin can you resolve the conflicts, I see scope meanwhile we are migrating the PR but I want to put focus on migration. You are most welcome to send PR for migration to jetpack compose.

**Comment by SekhGulamMainuddin** [comment]
Sure sir I will resolve the conflicts.

**Pull request closed without merging**
