### PR TITLE
Fix #1300 - contact us section is in the home fragment

### LINKED ISSUE #1300: The contact us section is in the home fragment
**Summary:**
As in almost every major app out there, the contact us section should be in the about us fragment (or the help fragment in some rare cases).
The home fragment's main purpose is to be a sort of a dashboard and the contact us section doesn't add up to that main functionality.
**Steps to reproduce:**
Just visit the home activity
**Expected behaviour:**
The contact us section should be in the about us fragment.
**Observed behaviour:**
The contact us section is in the home fragment.
**Device and Android version:**
This isn't related to android versions in any way.
**Screenshots:**

### PR DESCRIPTION
**Pull request by OHassini**
Fixes #1300 

Please Add Screenshots If there are any UI changes.
Screenshot_20200129-172651
Screenshot_20200129-174609
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by OHassini** [comment]
@luckyman20 @elirehema @geekanamika @jsahil730 Hi : ), please have a look !!

**Comment by OHassini** [comment]
Also build failure is not due to a problem in the code it's a server connection issue.

**Comment by rachittt** [comment]
can you update the screenshots? the link that you have provided is probably broken.

**Comment by OussEmaDevCode** [comment]
> can you update the screenshots? the link that you have provided is probably broken.

**Comment by OHassini** [comment]
@rachittt Try refreshing your page or checking your internet connection, the screenshots seem to work just fine on my instance

**Comment by ShivangiSingh17** [comment]
@OussEmaDevCode the contact us section in home page is more preferable as per the UI designing followed throughout all the user-facing applications of Mifos.

**Comment by OHassini** [comment]
ok cool !

**Comment by ShivangiSingh17** [comment]
Can you close the PR @OussEmaDevCode

**Pull request closed without merging**
