### PR TITLE
feat:offline support  in the home fragment wrt #1122

### LINKED ISSUE #1122: Offline support for the home screen.
**Summary:**

Currently the home screen shows empty spaces when no internet is available. I think a better alternative for better offline support would be saving basic informations like Name, Savings, Loan Amount in shared preferences when the internet is available. When internet is not available, it can load the same using last saved details locally.

**Steps to reproduce:**

Home Screen with no internet

**Expected behaviour:**

Basic details should be available without internet. It could be a step towards better offline support for the app.

**Observed behaviour:**

Blank spaces at respective fields.

**Device and Android version:**

Redmi Note 3

### PR DESCRIPTION
**Pull request by PratyushSingh07**
Fixes #1122 

Before the Change: 
https://user-images.githubusercontent.com/90026952/223648417-cabed712-84ce-4d88-aa56-5b2e7f06d48b.mp4

After the Change: 

https://user-images.githubusercontent.com/90026952/223648793-f86547b0-0321-4c66-841b-188d104a9e43.mp4

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi your thoughts on this feature? As the issue had mentioned this can be the first step in providing a better offline support to the app

**Comment by jawidMuhammadi** [comment]
- This PR includes codes not related to what is written in its title. It would be best to create new branches for each issue from the origin/openMF/development branch and also each PR should contain the changes/solution for the issue which has been linked not more than that.

- No, I don't think saving data objects in the shared preferences is a good idea as it is described in the description of the issue, because shared preferences are intended to be used to save small data in key-value formats. To support a proper offline first approach we would need to use a database that is out of scope at the moment.

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi fixed the PR

**Comment by PratyushSingh07** [comment]
its been long since we last interacted on this PR @jawidMuhammadi . Do you think that we can add this feature for the time being in our project ?

**Review by luckyman20 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
