### PR TITLE
fix#Issue676: Clicking Phone Number not opens Dialer

### LINKED ISSUE #676: Phone Number not opening Phone Dialer
**Summary:**

Phone Number on Home Fragment not opens dialer on clicking

**Steps to reproduce:**

Click on Phone Number on scrolling down

**Expected behaviour:**

Dialer should open

**Observed behaviour:**

Dialer is not opening

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

_phone_dialer_issue

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #676 

_phone_dialer_pr

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@dilpreet96 @droidchef @satyan Please review this PR and should I change the country code to another code ?

**Review by Rish02Sharma — CHANGES_REQUESTED** [review]
@miPlodder Thanks for the PR. 
I don't think you can directly hardcode the Indian country code.

**Comment by miPlodder** [comment]
@Rish02Sharma I have asked Repo Admins regarding the country code in the comment above. I will change the country code and update the PR, if they think other country code should be used .

**Comment by therajanmaurya** [comment]
This PR is not valid because we don't want to show the country code.

**Pull request closed without merging**
