### PR TITLE
feat: Added Malayalam translations for the application

### LINKED ISSUE #1050: Adding Malayalam translation feature to the App
**Summary:**
Adding Malayalam translation to make the application more viable.Adding this feature makes the application to be more multilingual, user-friendly and also widens its reach to common people at a great extent.

**Expected behaviour:**
Malayalam translation should be present under ```language``` drop-down list option.

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixes #1050 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by RajaVamsi11 — COMMENTED** [review]
@ShivangiSingh17 Can you please add screenshots of the app which is translated into Malayalam.

**Comment by ShivangiSingh17** [comment]
@therajanmaurya can you please review this PR.

**Comment by miPlodder** [comment]
@ShivangiSingh17 This won't work, add Malayalam to string.xml and a GIF also this change.

**Comment by ShivangiSingh17** [comment]
Ok I will surely do as you suggested.

**Review by RajaVamsi11 — COMMENTED** [review]
@ShivangiSingh17 Please squash your commits and also resolve conflicting files.

**Pull request closed without merging**
