### PR TITLE
Added Configurations for Dependabot

### LINKED ISSUE #1423: Automatic Bumping of Dependencies
**Summary:**
We need to have automatic Dependency Upgrading tool activated to facilitate better feature updates offered by newer versions of Library

**Expected behaviour:**
We need to enable a program called ```Dependabot``` available in Github MarketPlace which will help us by directly notifying for the dependency update.

**Would you like to work on this issue?**
Yes

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Fixes #1423 

Configuration for Dependabot has been created. The bot will automatically bump the version by sending a Pull Request Weekly. The bot will automatically re base the changes and resolve the conflicts.

Admin of the repository needs to enable the service on the repository by going to the[ Dependabot Page](https://github.com/marketplace/dependabot-preview) and clicking on Install Button will let everything done. It requires write access to the repository so I cannot do this step. Rest is to add the configuration file that has been added by this pull request.

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
Hi @ShivangiSingh17 Please help here, you mean by version with Gradle version too. am I right?

**Comment by ShivangiSingh17** [comment]
yes @therajanmaurya

**Comment by therajanmaurya** [comment]
I don't think so It's good idea to update the Gradle versions or library version. it may break the development. We update the library version until that we found any error in current one or we have  to update the library for new feature.

**Comment by therajanmaurya** [comment]
Let's talk broad. please send an email on Mifos mailing list and suggest this bot. I want to know if this really need or not. In my opinion we should not have it but still if you can convenience me. I am ok then.

**Comment by ShivangiSingh17** [comment]
Everytime a pull request will be created for the required updated version, it then depends on us whether we have to merge it or not.
This bot will help to keep all the things updated which is the biggest advantage I found about it.

**Comment by ShivangiSingh17** [comment]
> Let's talk broad. please send an email on Mifos mailing list and suggest this bot. I want to know if this really need or not. In my opinion we should not have it but still if you can convenience me. I am ok then.

okay sure
I will send a mail.

**Comment by therajanmaurya** [comment]
ok let's try this.

**Pull request merged**
