### PR TITLE
add splash screen

### LINKED ISSUE #697: White screen persisting for a short duration after opening app
**Summary:**

When opening the app, a white screen is shown for a certain duration of time.

**Steps to reproduce:**

Open application.

**Expected behaviour:**

The white screen should be replaced by a splash screen containing the logo of the application.

**Observed behaviour:**

The white screen persists.

**Device and Android version:**

Redmi Note 3 Android Version: 5.1.1 Stock

### PR DESCRIPTION
**Pull request by harshitbansal05**
Fixes #697

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@harshitbansal05 Please add Screenshot or GIF for above PR.

**Comment by mohak1712** [comment]
@harshitbansal05 Please follow the commit style guide
https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide

**Comment by harshitbansal05** [comment]
screenrecorder-2018-03-02-00-19-19-993

**Comment by miPlodder** [comment]
@harshitbansal05 I guess you can add **Mifos Initiative** below the image, will surely improve the UI for the Splash Screen.

**Comment by harshitbansal05** [comment]
@miPlodder this requires converting text to svg and then using it as a drawable in layer list. I could not find any good online tool that does this. So. how should I proceed?

**Comment by miPlodder** [comment]
@harshitbansal05 You can add new Mifos Logo from another Fineract-CN-mobile project, https://github.com/openMF/Fineract-CN-mobile/blob/development/app/src/main/res/drawable/mifos_logo_new.png .

**Comment by harshitbansal05** [comment]
@dilpreet96 @droidchef could you please review this?

**Comment by therajanmaurya** [comment]
@harshitbansal05 I really appreciate your PR but I am holding this PR for now because we had a discussion in the community and @dilpreet96 is implemented this feature in his local with many logics that we want to implement in splash screen as I had chat with him. 

@harshitbansal05 But for sure please mention this PR in your proposal we will consider your work.

**Comment by miPlodder** [comment]
Completed in another PR.

**Pull request closed without merging**
