### PR TITLE
fix: consecutive snackbars issue

### LINKED ISSUE #589: 2 Conflictling Snackbar Msg on Refreshing in Home Activity
**Summary:**

2 Conflictling Snackbar Msg on Refreshing in Home Activity, instead 1 Snackbar Msg should be shown

**Steps to reproduce:**

1) Open Home
2) Refresh using SwipeRefreshLayout.

**Expected behaviour:**

Message should come one after 1.

**Observed behaviour:**

1st msg is not visible and 2nd msg pops up over it.

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #589 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@dilpreet96 @therajanmaurya Please review this PR.

**Comment by miPlodder** [comment]
Can we use this Queue Snackbar Approach for all the Snackbar messages ? ( it will ensure that consecutive Snackbars are displayed properly)

**Comment by dilpreet2028** [comment]
Great work @miPlodder 
Instead of making a new function, refract the existing `show()` function and instead of creating a function which returns the callback rather add an anonymous object in the `addCallback()`.

**Comment by miPlodder** [comment]
@dilpreet96 Please review again, I have made the requested changes.

**Comment by dilpreet2028** [comment]
Good work @miPlodder

**Pull request merged**
