### PR TITLE
FilterIcon tint color Fixed #2357

### LINKED ISSUE #2357: Tint of Filter icon isnt visible in dark mode
**Summary:**

Tint of Filter icon is  on the darker side hence it isnt visible in the dark mode

**Steps to reproduce:**
- Go to Accounts
- Click on any Active Savings account from the list
- Click on Transactions
- Filter icon on the top right corner isnt visible in dark mode

**Expected behaviour:**

Filter icon on the top right corner should have been visible in dark mode

**Observed behaviour:**

 <table>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

**Device and Android version:**

Device: Pixel 7
Android: 13

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixed #2357
Filter Icon tint color fixed.

Please add #hacktoberfest on merge.

Screenshots:
<p>
 android
 android
</p>

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
can you identify the reason as to why the build is failing and fix it in this PR ?

**Comment by SekhGulamMainuddin** [comment]
Actually while building it on android studio it is working perfectly and generating the apk. But I am not able to figure out why it's failing here. And I guess there is some other problem because I have seen this in other PR's as well.

**Comment by PratyushSingh07** [comment]
run the  command `./gradlew assemble --stacktrace` , if you haven't already in your terminal to get the exact reason of this failure.  See if you can then fix ir

**Comment by SekhGulamMainuddin** [comment]
> run the  command `./gradlew assemble --stacktrace` , if you haven't already in your terminal to get the exact reason of this failure.  See if you can then fix ir

Ok

**Comment by SekhGulamMainuddin** [comment]
I have filed a new issue #2359 for the build checks failure in the workflow which is caused due to outdated functions usage.
I'll be adding a new PR on it in 3-4 days.

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya please merge my PR

**Comment by SekhGulamMainuddin** [comment]
Hi @therajanmaurya please merge my PR. 
On merge please add **hacktoberfest** tag

**Comment by therajanmaurya** [comment]
Rebase with development and fix build check

**Comment by SekhGulamMainuddin** [comment]
> Rebase with development and fix build check

Yes its passing all the checks.

image

**Pull request closed without merging**
