### PR TITLE
fix : replaced JCenter with mavenCentral

### LINKED ISSUE #1944: Replace JCenter with mavenCentral
**Summary:**

JCenter Maven repository is no longer receiving updates and it should be replaced with mavenCentral

### PR DESCRIPTION
**Pull request by gururani-abhishek**
Fixes #1944 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [☑️ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [☑️ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [☑️ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi did I do anything wrong? I'm not understanding why my PR isn't accepted. I took your permission to take the issue before making the PR.

**Comment by jawidMuhammadi** [comment]
Hey @gururani-abhishek, that is alright, it's my bad, I have closed the wrong one, there was another PR too.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi no worries mate. Well, what should I do now? Should I make a new PR?

**Comment by jawidMuhammadi** [comment]
@gururani-abhishek No, it is not required. We already have another PR pending for the same issue.

**Pull request closed without merging**
