### PR TITLE
Unneccessary nullable Removed

### LINKED ISSUE #1862: Too many unneccessary nullable variables
This is probably because of Java to Kotlin conversion. Many class properties, variables, function arguments and return type can be made non-nullable.

### PR DESCRIPTION
**Pull request by arinmodi**
Fixes #1862

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

### CODE REVIEW

**Review by rahul-gill — APPROVED** [review]
You can merge the changes to last commit with `git commit --amend`

**Comment by arinmodi** [comment]
@rahul-gill, merged into single commit

**Comment by arinmodi** [comment]
@rahul-gill, can you please review this ?

**Review by rahul-gill — APPROVED** [review]

**Comment by arinmodi** [comment]
Thanks for approving, but when will this PR merge ?

**Comment by arinmodi** [comment]
> @rahul-gill, can you please review this ?

@rahul-gill, please reply

**Comment by rahul-gill** [comment]
> > @rahul-gill, can you please review this ?
> 
> @rahul-gill, please reply

I don't have repository access

**Comment by arinmodi** [comment]
So @rahul-gill, how will this PR merge ?

**Pull request merged**
