### PR TITLE
Fixed an error during Login

### LINKED ISSUE #1896: Error during Login/SignUp
**Summary:**
Unable to login into mifos using the credentials (username : mifos  ; password : password).  

**Steps to reproduce:**

- Start the app 
- Go to login and enter the above credentails nothing happens
- this is the logcat : {"timestamp":"2023-02-01T15:33:29.740+00:00","status":400,"error":"Bad Request","path":"/fineract-provider/api/v1/self/authentication"}

**Expected behaviour:**

User should have been able to login using these credentails 

**Observed behaviour:**

I get the response when i pass the header to https://demo.mifos.community/fineract-provider/api/v1/clients
image

**Device and Android version:**

Device : OnePlus Nord<br> Android 12

### PR DESCRIPTION
**Pull request by Aditya-gupta99**
Fixes #1896 

https://user-images.githubusercontent.com/94394661/216349531-83d513c6-6b25-4ed4-a4a2-1ecad739c7ec.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Aditya-gupta99** [comment]
@rahul-gill @IOhacker Kindly review my pr

**Comment by rahul-gill** [comment]
See if removing 'self' from the url alone fixes the issue

**Comment by Aditya-gupta99** [comment]
@rahul-gill No i tried removing self but it did'nt work

**Comment by kingbass01** [comment]
The issue still exists for me.
Can anyone please confirm if it's fixed?

**Comment by jawidMuhammadi** [comment]
@kingbass01 Could you please open an issue by posting the logs in the description?

**Comment by kingbass01** [comment]
Yeah, sure!
Here it is #1936

**Pull request merged**
