### PR TITLE
fix: #1691 Initialized the list in Summary.kt

### LINKED ISSUE #1691: App Crashes when going to background in Saving Account Details
**Summary:**
App Crashes when going to the background in Saving Account Details

**Steps to reproduce:**
1. Open Account from the dashboard
2. Open an application
3. Go in background
4. Observe

**Expected behaviour:**
App goes in background

**Observed behaviour:**
App crashes

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/104419865-1aa34200-559f-11eb-9ef5-4d06b40f017a.mp4

**Crash Log:**

[log.txt](https://github.com/openMF/mifos-mobile/files/5807034/log.txt)

### PR DESCRIPTION
**Pull request by divyank00**
Fixes #1691

Please Add Screenshots If there are any UI changes.

https://user-images.githubusercontent.com/50913976/104422360-abc7e800-55a2-11eb-8d03-6691929c6ed6.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
@devansh-299 please review it

**Comment by divyank00** [comment]
@miPlodder please review it

**Review by PatelVatsalB21 — APPROVED** [review]
LGTM

**Review by miPlodder — APPROVED** [review]
Good Job

**Pull request merged**
