### PR TITLE
feat:Payment hub

### PR DESCRIPTION
**Pull request by ShivangiSingh17**
Work left:
    Fetching the secondary identifier during the login process.
    Adding the payment details in the saving and charges section
    Update and Reduce the amount transaction done from the original amount in the Home section.

Screenshots
frame_020_delay-0 1s

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@ShivangiSingh17 can we fix the conflict?

**Comment by garvit984** [comment]
@ShivangiSingh17 Please remove these conflicts so that we can merge this PR.

**Comment by Sparsh1212** [comment]
If this is still up for grab, I would love to work on this. Also, please guide me on how to get started on this.

**Comment by garvit984** [comment]
You can check the documentation in the Readme. @Sparsh1212

**Comment by garvit984** [comment]
You can also refer this PR from wallet. https://github.com/openMF/mobile-wallet/pull/1009

**Comment by miPlodder** [comment]
I don't see any issue mapped to this PR. I am creating an issue for the same. So all the requirements are in one place wrt integration.

@garvit984 Can you add some details for the same here in this ticket,  https://github.com/openMF/mifos-mobile/issues/1617
@Sparsh1212 Please assign the newly created ticket to you. Go ahead with the implementation

Closing this PR, since its depreciated now

**Pull request closed without merging**
