### PR TITLE
Feat: Add Arabic translations

### PR DESCRIPTION
**Pull request by m-sameer**
image
image
image
image

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by m-sameer** [comment]
The command `./gradlew check` was failing because of illegal escape sequences in other languages so I have edited those files too to fix the build.

**Review by luckyman20 — APPROVED** [review]
Looks good!

**Comment by luckyman20** [comment]
@m-sameer Please add few more screenshots

**Comment by m-sameer** [comment]
@luckyman20 Done!

**Pull request merged**
