### PR TITLE
Fix #1204 - Fixes filters cleared when layout is refreshed

### LINKED ISSUE #1204: Filters cleared when layout is refreshed
**Summary:**

When swipe to refresh is used to refresh accounts activity , the filters applied (if any) are removed

**Steps to reproduce:**

Accounts activity --> Apply filters --> Swipe to refresh

**Expected behaviour:**

Swipe to refresh should have refreshed the layout while preserving the filters i.e. it should have refreshed among the filtered list 

**Observed behaviour:**

Filters were lost.

**Device and Android version:**

Xiaomi Poco F1
Android 9
Stock rom

**Screen Recording:**

GIF-191017_184249

### PR DESCRIPTION
**Pull request by OHassini**
Fixes #1204 

Please Add Screenshots If there are any UI changes.
video2gif_20191209_175612

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by harshshinde07 — APPROVED** [review]
Well done :)

**Review by elirehema — CHANGES_REQUESTED** [review]
@OussEmaDevCode this solution disabled application scrolling functionality. I think there is a something wrong with `setAdapter( )` function :smile:

**Comment by OHassini** [comment]
@elirehema Hi : ), I am sorry but I didn't understand what did you mean by "disabled application scrolling functionality"? The app still scrolls fine on my instance.

**Comment by elirehema** [comment]
> @elirehema Hi : ), I am sorry but I didn't understand what did you mean by "disabled application scrolling functionality"? The app still scrolls fine on my instance.

@OussEmaDevCode i mean recyclerview is not scrolling up or down.

**Comment by OHassini** [comment]
@elirehema I am sorry but I am not experiencing any issues it still scrolls perfectly fine here's a [link](https://photos.app.goo.gl/U1U9ZAigd9qcpSh47) to show you my instance.

**Review by elirehema — APPROVED** [review]
Keep a good job @OussEmaDevCode :+1:

**Comment by OHassini** [comment]
@elirehema thanks, I resubmitted the task for review, hope it's fine now : ).

**Pull request closed without merging**
