### PR TITLE
 fix #2486 :  updated home activity onResume logic to solve the profile photo bug 

### LINKED ISSUE #2486: Bug : profile photo not visible after changing theme , need to refresh
**Summary:**

While we change the theme of the app  , the profile photo is not visible in home page 

**Steps to reproduce:**

1. Open the app 
2. change the theme of the app . 
3. observe the profile photo in home page  

**Expected behaviour:**

Profile photo should be clearly visible despite changing profile photo  

**Observed behaviour:**

when we normally open the app, the profile photo is normally visible . But  , when we change the app theme , the profile photo seems go nowhere. The space of the profile photo is observed empty  and the profile photo is invisible  .
**Device and Android version:**

Redm 9A , android version : 10 

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/25600880/8ffceb86-1a09-4a0f-b9ec-a8530e1e4277

### PR DESCRIPTION
**Pull request by NiranjanNlc**
Fixes #2486 

Profile photo clearly visible while changing between dark and light mode . 

https://github.com/openMF/mifos-mobile/assets/25600880/fa33702c-d76a-483f-9982-701311523a2a

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
you are changing system theme . Does it work after changing the theme from inside of the app ?

**Comment by NiranjanNlc** [comment]
> you are changing system theme . Does it work after changing the theme from inside of the app ?


Yeah , i have updated the screen recorder video of description  and added the commit . 

@PratyushSingh07  Please review and provide some suggestion.

**Comment by AvneetSingh2001** [comment]
There is a similar bug in Profile photo of Navigation Drawer. Can you check that also @NiranjanNlc

**Comment by NiranjanNlc** [comment]
> There is a similar bug in Profile photo of Navigation Drawer. Can you check that also @NiranjanNlc

yeah i had found it  , since this pull request solved for both cases , so did not think of raising  next issues . 
Please conform from   the screen-cast  I attached in the pull request description.

**Pull request closed without merging**
