### PR TITLE
fix : Search Bar Allignment Issue

### LINKED ISSUE #976: Filter icon is not aligned properly while using Search in Account
**Summary:**

Filter icon is displaced while using search option, which leads to bad UI.

**Steps to reproduce:**

1. Go to Accounts.
2. Open search bar

**Expected behaviour:**

Either this should be fixed, or maybe we can remove the filter option while user is using the search bar.

**Observed behaviour:**

e1a3c282-2213-481b-b7a9-231849bf1033

**Screenshots:**
Added.
***Phone**
Redmi Note5 pro 
Android 8.1.0

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #976 

Fixed this issue as per device width. (I saw it was fixed as well, but the solution didnt work for all devices.)

Please Add Screenshots If there are any UI changes.
image
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@luckyman20  @ankurs287

**Comment by therajanmaurya** [comment]
@shiv07tiwari Good Job, You are right https://github.com/openMF/mifos-mobile/issues/976#issuecomment-452709483. We don't need the filter option while searching. Please make the changes 
1. Hide filter option if the search option is visible. 
2. When the search option is visible and the user clicks the back button and close the keyboard and if there is no text in the search box then search box should be closed and show search and filter menu button.

Please make changes and let me know. I will review and merge.

**Comment by shiv07tiwari** [comment]
Thanks @therajanmaurya 
I talked to @luckyman20 about the comment, and we think the their might be a case while user is searching, but may still apply filters for better crisp results.
So, is this a considerable use-case, or should I remove the filter option completely as per your suggestion ?

**Comment by therajanmaurya** [comment]
@shiv07tiwari Ohhh, I appreciate your thoughts and I am happy to say you and @luckyman20 are right about this. Sorry I missed this scenario. 

Good Job. Let me review and merge.

**Comment by shiv07tiwari** [comment]
@therajanmaurya Thanks a lot.

**Pull request merged**
