### PR TITLE
Fix #686:Action Bar Slides in case Add Beneficiary fragment

### LINKED ISSUE #686: Action Bar Slides in case Add Beneficiary fragment
**Summary:**

On moving down in screen the action slides upwards instead of View section thus making clicking the navbar drawer difficult and overlaps notification panel which creates hinderance in UX.

**Steps to reproduce:**

1)Run the app
2)Add Beneficiary
3)Keep on filling the from details

**Expected behaviour:**

The action bar should be immobile

**Observed behaviour:**

The action bar is mobile.

**Device and Android version:**

Android 5.0.2,API 21

**Screenshots:**

I want to work on this.

### PR DESCRIPTION
**Pull request by AkshGautam**
Fixes #686 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96 Please review.

**Comment by therajanmaurya** [comment]
Looks good, One more change  I want that I want this feature in separate activity, as the user will click on Add  Beneficiary  Fab button It should not replace fragment it should open in a new activity.
you can this in new PR, for Now, I am merging this PR.

**Comment by AkshGautam** [comment]
@therajanmaurya sure would do that change. Should I create a new issue for this or directly submit a PR?Thanks

**Comment by therajanmaurya** [comment]
yes please open new PR for that.

**Comment by AkshGautam** [comment]
sure I am working on it.

**Pull request merged**
