### PR TITLE
Fixes #1153: Fixed the aligment of account number

### LINKED ISSUE #1153: Centralise the account number text
The text for account number should also be in centre so as to improve the UI.
Screenshot_2019-04-03-11-32-57-405_org mifos mobile

### PR DESCRIPTION
**Pull request by jatinkumarg**
Fixes #1153 

New changes
apply_for_loan

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@jatinkumarg You should first ask the person who has opened the issue, and if he is not working on it, then only should send a PR.

**Comment by jatinkumarg** [comment]
@shiv07tiwari Apologies, since there was no one assigned to the https://github.com/openMF/mifos-mobile/issues/1153 and the issue has been open for 12 days, I thought anyone can fix this issue.

So I submitted this PR 14 hours ago and then I saw you submitted another PR with the same fix just three hours ago.

Look I was just trying to help. But now I am kind of disappointed with the professionalism in this Open Source community. I hope you understand my point of view.

**Comment by RajaVamsi11** [comment]
@jatinkumarg It okay but try not to make this mistake again.

**Comment by shiv07tiwari** [comment]
@jatinkumarg Its not about the professionalism, but is about following the basic rules of open source contributions. We all are here to help and solve the issues.

**Pull request closed without merging**
