### PR TITLE
Refactor: LoanAccount details #84

### PR DESCRIPTION
**Pull request by dilpreet2028**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
Don't you think It is not following google material guidelines according to UI. Try to make button color primary or something else.

**Comment by dilpreet2028** [comment]
Changed according to the review

**Comment by therajanmaurya** [comment]
Looks good, please make "Make payment" button to primary also.

**Comment by dilpreet2028** [comment]
Done :)

**Pull request merged**
