### PR TITLE
refactor : Issue#701 - Removed redundant type casting

### LINKED ISSUE #701: Remove redundant  casting in the project.
**Summary**
Remove redundant type cast from the project.In the project at many places we are using redundant type cast  e.g : ``` TextView tv = (TextView)findViewById(R.id.xxxx)```.
I think will be good for code clean up plus we are using butterknife so it will be better to use that.

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #701

Removed redundant typecasting from the project as code clean up.

### CODE REVIEW

**Review by Rish02Sharma — COMMENTED** [review]
Hey @ivary43 , Are you sure that removing this will not break anything in the app?

**Comment by therajanmaurya** [comment]
@ivary43 Looks good please follow the commit guide lines https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide and squash your commits.

**Comment by ivary43** [comment]
@Rish02Sharma  i think only removing a redundant type cast won't break anything.

**Comment by ivary43** [comment]
@therajanmaurya  i have squashed the commits.

**Comment by ivary43** [comment]
@therajanmaurya done, please review.

**Comment by therajanmaurya** [comment]
@ivary43 I don't think you have read the commit guidelines, according to guidelines your commit message should consist prefix of your change like you are not changing any logic so your commit message would be `refactor: Removed redundant typecasting`

change the commit message and let me know, rest of things are good.

**Comment by ivary43** [comment]
@therajanmaurya  done.

**Pull request merged**
