### PR TITLE
Snackbar Fix (#899)

### LINKED ISSUE #899: Recent Transaction Fragment shows Snackbar every time on opening
**Summary:**

Recent Transaction Fragment shows Snackbar every time on opening

**Steps to reproduce:**

Go to Navigation Drawer > Recent Tranactions

**Expected behaviour:**

Snackbar should not pop up everytime. (no need to show the snackbar)

**Observed behaviour:**

Instead, it pops up everytime

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by migueldinisdev**
Fixes #899 

Removed _"No more transactions available"_ snackbar from the app.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

Not sure how I should proceed about the squashing.

Awaiting response.

### CODE REVIEW

**Comment by migueldinisdev** [comment]
Update:

I noticed 2 "build failed" messages (from bots, I guess) and analyzed their details. There is a problem with the MultiDEX library and I'm sure it doesn't have nothing to do with my code - you can analyze my changes to confirm it. I'm not sure what's causing the bots to fail - I only know that they are failing in the second commit (where I removed the strings from the XMLs).

**Comment by letelete** [comment]
I had the same problem with MultiDex. The solution was to change the order of repos in build.gradle. Check out #907 for more details.

**Comment by migueldinisdev** [comment]
@letelete Thanks for the help.

I'm not sure if it's a good practice to change build.gradle file. Anyway, my build.gradle and the main project's one are the same because I didn't change them. I'll still wait for a human review :P

**Comment by letelete** [comment]
Neither I did change anything with top project files. Just cloned the repo and faced this issue already.

**Comment by migueldinisdev** [comment]
@letelete It's weird to be honest. I noticed a mentor wrote a comment in your PR to remove the commit in which you switched the lines in build.gradle

**Comment by miPlodder** [comment]
@MigDinny Fix the Build and [squash](http://www.jancarloviray.com/blog/how-to-merge-multiple-commits-into-one-git-commit/) the commits.

**Comment by migueldinisdev** [comment]
@miPlodder I cannot fix it. It is working on my computer, so there is no way I can fix it. #909 probably fixes it, though.

**Pull request closed without merging**
