### PR TITLE
Fix: #1573 Checked if position is not outOfIndex and rectified the code logic

### LINKED ISSUE #1573: App crashes on pressing back button on review loan page
**Summary:**
On Review loan page if back button from toolbar or back button is pressed app crashes. Problem is with Purpose of Loan spinner

**Expected behaviour:**
It should load all selected and entered values on Submit loan page

**Device and Android version:**
Lenovo Tab7 
Android 7.0
Stock ROM

Screenshot_20201126-235513
Screenshot_20201126-235526

### PR DESCRIPTION
**Pull request by divyank00**
Fixes #1573 & #1680

https://user-images.githubusercontent.com/50913976/103819593-b9f0a280-5090-11eb-9f05-e962dbf89bd4.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
@miPlodder Can you please review this

**Comment by PatelVatsalB21** [comment]
@divyank00 Its great you a better solution. But if possible don't create redundant issues as #1573 was already made, there was no need for #1680. Thank you :)

**Comment by divyank00** [comment]
> @divyank00 Its great you a better solution. But if possible don't create redundant issues as #1573 was already made, there was no need for #1680. Thank you :)

I felt both issues are different, Issue #1573 was due to null pointer and I observed Issue #1680 while studying that file.

Still will keep in mind, Thanks 😊

@PatelVatsalB21 Can you review it please

**Comment by PatelVatsalB21** [comment]
@divyank I can review but i don't have write access. So it wont help much.

**Comment by divyank00** [comment]
@devansh-299 Can you please review it

**Comment by divyank00** [comment]
@miPlodder @devansh-299 
Can you please review it

**Comment by divyank00** [comment]
@miPlodder Can you please review this. This was a major issue🙂

**Pull request closed without merging**
