### PR TITLE
Fix #688: Login fails after entering correct passcode for the fourth time after 3 wrong tries.

### LINKED ISSUE #688: Login fails after entering correct passcode for the fourth time after 3 wrong tries.
**Summary:**

The login to app fails if the user enters the correct passcode after 3 wrong tries.
PS 1234 is the correct passcode here.

**Steps to reproduce:**

1)Run the appp
2)Enter wrong passcode 3 times
3)Enter correct passcode
4)Login fails and login activity is presented

**Expected behaviour:**

The app should login on correct passcode enter on 4th time even if previous 3 were wrong and should open login activity if 4th attempt is also wrong.

**Observed behaviour:**

The app fails to login on correct passcode in 4th try.

**Screenshots:**

I am working on this.

### PR DESCRIPTION
**Pull request by AkshGautam**
Fixes #688 

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by AkshGautam** [comment]
@dilpreet96 @therajanmaurya Please review.

**Comment by therajanmaurya** [comment]
@AkshGautam Please fix the conflicts and @dilpreet96 Please follow this PR.

**Comment by AkshGautam** [comment]
@therajanmaurya sure would resolve them. Thanks

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I have resolved the conflicts.please review.

**Comment by prashantkh19** [comment]
@AkshGautam The passcode implementation is moved to a separate library repository. I guess we should address this issue there. Make this PR in that repository.
@therajanmaurya @geekanamika I think we should close this PR.

**Comment by geekanamika** [comment]
Closing the PR as it needs to be handled in [passcode](https://github.com/openMF/mifos-passcode) repository.

**Comment by therajanmaurya** [comment]
I transferred this issue to Passcode library

**Pull request closed without merging**
