### PR TITLE
refractor: Login And Passcode Activity UI

### PR DESCRIPTION
**Pull request by dilpreet2028**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@dilpreet96 fix the conflicts

**Comment by therajanmaurya** [comment]
@dilpreet96 I can't see the password show and hide button.

**Comment by dilpreet96** [comment]
Sorry I forgot about that. Sending PR

**Comment by dilpreet2028** [comment]
@therajanmaurya Sorry I forgot about that. PR updated

**Pull request merged**
