### PR TITLE
Fix: Next click on text input in Add beneficiary screen

### LINKED ISSUE #612: Next in Beneficiary screen does not work
**Summary:**

In Add Beneficiary screen when adding values to various fields pressing enter moves the data up and does not take user to the next field

**Steps to reproduce:**

Go to Manage Beneficiaries -> Add -> Add values

**Expected behaviour:**

When adding values the pressing next the user should automatically be transferred to the next field rather than they themselves clicking the next field every time.

**Observed behaviour:**

When next is pressed on a field the data hides (moves up) rather than taking user to the next field. Only the transfer limit section works but all should work similarly

**Device and Android version:**

LeEco2(6.0)

**Screenshots:**

error

I would like to work on this issue

### PR DESCRIPTION
**Pull request by mohak1712**
Fixes #612 

Please Add Screenshots If any UI changes.

fix

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mohak1712** [comment]
@therajanmaurya , @dilpreet96 please review.

**Comment by dilpreet2028** [comment]
Can you change the commit message to 'fix: Next click on text input in AddBeneficiary screen'

**Comment by mohak1712** [comment]
ya sure @dilpreet96

**Comment by mohak1712** [comment]
@dilpreet96 done. Please review

**Pull request merged**
