### PR TITLE
Fix #678 : Change visibility of ProgressBar on Fragment change

### LINKED ISSUE #678: Progress Bar does not change it visiblity
**Summary:**

Progress Bar shows infinity while creating Beneficiary

**Steps to reproduce:**

Go to Beneficiaries
Add Beneficiary 
Scan QR Code (w/o QR that is via Add, it works sometimes, and behaves same as below sometimes)

**Expected behaviour:**

Progress Bar should not be visible 

**Observed behaviour:**

Progress Bar is visible (even on other fragments)

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

issue_beneficiary_infinite_progress_bar

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #678 

**(Before)**
pr_progress_bar_before

**(After)**
pr_progress_bar_after

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @droidchef @satyan Please review this PR.

**Comment by therajanmaurya** [comment]
@miPlodder I don't want this solution but good catch for fixing this issue can you please open this Add Beneficiary in new activity instead of fragment transaction.

**Comment by miPlodder** [comment]
@therajanmaurya I will open Add Beneficiary in new Activity and update the PR. What should I do for other fragments where this issue persists like in  TPT ?

**Comment by AkshGautam** [comment]
@therajanmaurya As suggested by you in PR #705 . I have already started working on adding the beneficiary to a new activity modification and already created an issue for the same #722 .Should I continue?

**Comment by miPlodder** [comment]
@therajanmaurya Can you help us here on how to proceed ?

**Comment by therajanmaurya** [comment]
@miPlodder I gave the same review in two places sorry for that @AkshGautam Please go ahead and make PR for that and @miPlodder your PR makes sense. I am merging this now.

**Comment by therajanmaurya** [comment]
and The developer wrote this feature, he has to make this thing, maybe he forgets it. Keep finding bugs and send PR.

**Pull request merged**
