### PR TITLE
Fixes #1566: No Network app crash fixed

### LINKED ISSUE #1566: App crashes on no internet
**Summary:**
If app is started by user without internet connection and clicked on login or register it should show toast as "Please check your internet connection" instead app crashes.

**Steps to reproduce:**

Turn off Internet/Wifi
Open app
Click on Login or fill all details in register section and click on register

**Expected behaviour:**

If app is started without internet connection and login or register is clicked it should show toast message

**Observed behaviour:**
App crashes when clicked login or register button without internet

**Device and Android version:**

Lenovo Tab 7
Android 7.0(Nougat)
Stock ROM

**Screenshots:**

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1566 

Screenshot_20201121-131404

**Stacktrace of Error**
Capture

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by miPlodder — COMMENTED** [review]
- Follow these https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide
- Can we attach `stacktrace` for the crash?

**Comment by PatelVatsalB21** [comment]
Do you want me to attach stacktrace? I can but it was simple null pointer exception.  Also i followed your instructions i.e. 3 checkboxes taken care of and 1 commit

**Comment by miPlodder** [comment]
Looking at fix, it looks like NPE fix. Yes, attach stacktrace for app
crashes issues. It provides more details about the issue.

Even add an item in PR template, for attaching the stacktrace for app
crashes.

**Comment by PatelVatsalB21** [comment]
2020-11-29 23:44:23.656 14284-14284/org.mifos.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobile, PID: 14284
    java.lang.IllegalStateException: cm.activeNetworkInfo must not be null
        at org.mifos.mobile.utils.Network.getNetworkInfo(Network.kt:20)
        at org.mifos.mobile.utils.Network.isConnected(Network.kt:31)
        at org.mifos.mobile.ui.activities.LoginActivity.onLoginClicked(LoginActivity.kt:129)
        at org.mifos.mobile.ui.activities.LoginActivity$$ViewBinder$1.doClick(LoginActivity$$ViewBinder.java:24)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5675)
        at android.view.View$PerformClick.run(View.java:22641)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
2020-11-29 23:44:24.280 13796-13796/? E/OverlaySController: Calling with an invalid UID, the interface will not work
2020-11-29 23:44:24.281 13796-13796/? E/OverlaySController: Invalid version
2020-11-29 23:44:24.287 13796-13796/? E/OverlaySController: Only system apps are allowed to connect

Capture

**Review by miPlodder — APPROVED** [review]

**Comment by miPlodder** [comment]
LGTM
- can we follow standard commit msg style, https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide
for reference, `fix #issue-id: commit-msg`

**Comment by PatelVatsalB21** [comment]
Sorry I will take care of it

**Comment by miPlodder** [comment]
@PatelVatsalB21 `fix #1566: No Network app crash fixed` use this commit message.

1. `git commit --amend`
2. update the commit message which I have to give
3. Then force push, `git push -f <remotename> <branchname>`

**Review by miPlodder — APPROVED** [review]

**Comment by miPlodder** [comment]
Good job

**Pull request merged**
