### PR TITLE
Fix #399 - Display currency symbol before the total deposit amount

### LINKED ISSUE #399: Dollar sign is displayed after amount in total deposit
**Summary:**
Dollar(currency) is displayed after the amount.
It should be displayed before the amount.
**Steps to reproduce:**
Open any accounts details

**Expected behavior:**
Currency symbol should be displayed before the amount.

**Observed behavior:**
Currency symbol was displayed after the amount
**Device and Android version:**
Samsung Galaxy A5(2016)

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by mayank8318**
Fixes #399 

**Fixed UI change**:
image

Please make sure these boxes are checked before submitting your pull request - thanks!

- [:+1:] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [:+1:] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ :+1: ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@mayank8318 Welcome to the community, Can you please follow the commit style guidelines https://github.com/openMF/self-service-app/wiki/Commit-Style-Guide and for future please read contribution guidelines in case you will miss in your next PR.

**Comment by therajanmaurya** [comment]
PR looks good to me, Only you need to follow commit style guidelines.

**Comment by mayank8318** [comment]
Yes I read them. Have I missed something?
Please guide me if I have
Thanks!

**Comment by therajanmaurya** [comment]
Yes, you commit message should be like this `fix: Display currency symbol before the total deposit amount in SavingAccountsDetailFragment`

You can change commit message using this command `git commit --amend`

**Comment by mayank8318** [comment]
@therajanmaurya Sorry I missed that. I did the required changes.

**Comment by therajanmaurya** [comment]
@mayank8318 I think you changed the commit message `Fix #399 - Display currency symbol before the total deposit amount in SavingAccountsDetailFragment` but your commit message should be ` fix: Display currency symbol before the total deposit amount in SavingAccountsDetailFragment`. Please make the changes and force push again.

**Comment by mayank8318** [comment]
@therajanmaurya Done :)

**Comment by therajanmaurya** [comment]
Great 👍

**Pull request merged**
