### PR TITLE
fix: Issue #473

### LINKED ISSUE #473: Give preference to Account Balance shown in Savings and Loan Account Details
**Summary:**

Account Balance shown in Savings and Loan Account Details should be given more preference than other things shown.

 
Shift Account Balance to the top and increase it's size and make the amount bold.

### PR DESCRIPTION
**Pull request by luckyman20**
Fixes #473

### CODE REVIEW

**Comment by dilpreet2028** [comment]
@luckyman000786 you also have to give preference to Outstanding balance in Loan Account Detail and add screenshot for both the screens.
Try to follow commit style :- https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide

**Comment by luckyman20** [comment]
screenshot_20171202-202824 1

Loan Account Details

**Comment by luckyman20** [comment]
screenshot_20171202-202812 1

Savings Account Detail

**Comment by luckyman20** [comment]
@dilpreet96 Please review it now!

**Review by dilpreet2028 — APPROVED** [review]

**Pull request merged**
